- src/cljs/athens/subs.cljs
Needs a unit test like in [the comment](https://github.com/athensresearch/athens/compare/master...jeroenvandijk:feature/sort-blocks-recursively?expand=1#diff-8777c8d06ff3c66fc600f034b36aeae6R66-R83) #15
> Sort blocks recursively #12

- .clj-kondo/config.edn
- .github/workflows/build.yml
- .gitignore
- script/lint
`clj-kondo` is an extra shield that will help us with:
* Unused variables, namespaces, shadowing, typos
* Adhere to generally accepted clojure code style (mostly coming from https://github.com/bbatsov/clojure-style-guide)
* Adhere to generally accepted clojure idioms
> Add clj-kondo script + build step

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
These Github issue templates will help us structure the incoming information via Github issues
@tangjeff0 Maybe may you want to tweak them with links to [Contributing](https://github.com/athensresearch/athens/blob/master/CONTRIBUTING.md)
> Add GitHub issue template

- project.clj
- src/cljs/athens/page.cljs
- src/cljs/athens/style.cljs
- src/cljs/athens/views.cljs
See #10. This uses [Garden](https://github.com/noprompt/garden) for some basic styling. Now, the body uses the browser's default sans-serif font, instead of not specifying one (some browsers use Time New Roman in this case, some use Arial, some use Tinos (a Times New Roman clone)). Also, it makes sure there is enough room for the dates on the home page.
I'm not very experienced with Clojure, but it does appear to work correctly to me.
> Add basic styling

- .clj-kondo/config.edn
- .github/workflows/build.yml
- src/cljs/athens/style.cljs
- src/cljs/athens/views.cljs
- test/athens/block_test.clj
This PR fixes the clj-kondo config.
The PR 
- Removes things that are specific to clj-kondo's own code
- Fixes additional lint warnings.
- Updates the clj-kondo version in Github actions
- Cleans up whitespace in build.yml file
cc @jeroenvandijk
> [#39] Fix more lint warnings, adapt config.edn

- src/cljs/athens/page.cljs
- src/cljs/athens/parser.cljs
- src/cljs/athens/router.cljs
Added :content-editable HTML attribute to text and title
- Discussion on rationale is found in #70.
Refactored navigate-page and toggle-open re-frame functions into athens.router namespace
- Reason given in #70
> Editable blocks refactor

- doc/ClojureFam.md
I'm excited to announce the pilot for ClojureFam, a program to partner **Clojure Learners** with one another, as well as with **Clojure Mentors**. [Please read about the entire program](https://github.com/athensresearch/athens/blob/ClojureFam/doc/ClojureFam.md), make comments directly on the diffs, and discuss below.
Note: this first week will be piloted only with current Athenians. If you are interested in becoming a Learner or Mentor for later cohorts, sign-up using the links in the markdown file. 🙂
> ClojureFam, an initiative to pair Clojure Learners and Mentors together

- .clj-kondo/config.edn
- script/lint
- src/cljs/athens/page.cljs
- src/cljs/athens/style.cljs
`script/lint` output before this change:
~~~
src/cljs/athens/page.cljs:6:38: warning: #'re-frame.core/dispatch is referred but never used
src/cljs/athens/style.cljs:38:46: warning: Unresolved namespace clojure.string. Are you missing a require?
src/cljs/athens/style.cljs:62:41: warning: unused binding e
linting took 137ms, errors: 0, warnings: 3
[FIXME] fix above warnings and remove this warning
~~~
`script/lint` output after this change:
~~~
linting took 141ms, errors: 0, warnings: 0
~~~
I wasn’t sure if it was right to assume that the `clojure.string` namespace is always available, so I tested it by creating and running the following standalone file:
~~~clj
#!/usr/bin/env boot
(defn -main [& _args]
(println (clojure.string/join "|" [1 2 3])))
~~~
Since that program printed “1|2|3” with …
> fix: remaining clj-kondo lint warnings

- src/cljs/athens/parser.cljs
This will help users of the current version understand why there is red text everywhere, and help developers debug the parse failures. Example title text after this change:
> parse error at line 1 col 1: [{:tag :string, :expecting "#"} {:tag :string, :expecting "(("} {:tag :string, :expecting "[["} {:tag :regexp, :expecting #"^(\w|\s)+", :full true}]
> <img width="549" alt="example title text with parse failure error message" src="https://user-images.githubusercontent.com/79168/82653952-fa78da00-9bed-11ea-81de-eba3122c697b.png">
I renamed the `str` parameter to `string` so I could use the `clojure.core/str` function as `str`.
> feat: add title text with parse failure error messages

- src/cljs/athens/page.cljs
Next step in dealing with #62. Haven't yet dealt with #61 and #66. I've also realized that I should deal with renames that include `#hash-style-links` being renamed to `#[[title that includes whitespace]]`.
I don't really expect this to be merged yet until I deal with these issues, but would appreciate some feedback whether I'm on the right track with this.
> Adds title component that supports page renaming

- src/cljs/athens/page.cljs
- src/cljs/athens/parse_renderer.cljs
We were going to remove it at some point because in a change of plans, we decided to implement the first version of editing using textareas instead of contentEditable. I’m doing the removal now to solve these two problems caused by contentEditable:
- It causes React to output warnings to the browser console, cluttering the console output:
> Warning: A component is `contentEditable` and contains `children` managed by React. It is now your responsibility to guarantee that none of those nodes are unexpectedly modified or duplicated. This is probably not intentional.
- It prevents links within blocks from being clicked: clicking a link just places the cursor there.
> fix: remove content-editable

- .gitignore
The `.cpcache` directory was created after I installed the `clojure` binary and ran `script/carve`.
`.cpcache` is described here: https://clojure.org/reference/deps_and_cli#_directories
> fix: add .cpcache to .gitignore

- src/cljs/athens/events.cljs
- src/cljs/athens/page.cljs
- src/cljs/athens/router.cljs
- src/cljs/athens/subs.cljs
First work on #61. The (very ugly) prompt does appear when trying to rename to a page title that already exists. I do have some questions about completing this PR:
- Are there conventions about how re-frame's app db should be structured?
- What should happen when a user navigates away from the page without responding to the prompt? Maybe the `:navigated` event should clear it?
- Should the transaction to do the actual merge be part of this PR?
> Adds merge prompt

- src/cljc/athens/parser.cljc
- src/cljs/athens/parse_renderer.cljs
- test/athens/parser_test.clj
This PR is a draft because it’s built on top of the commits in PR #102. That PR must be reviewed and merged first. Only the commit “feat(parsing): basic support for URL links” is new to this PR.
> feat(parsing): basic support for URL links

- resources/public/cards.html
- src/cljs/athens/devcards/style_guide.cljs
@tangjeff0 This is one way how you could import the font face
> Use IBM Plex Sans font

- src/cljs/athens/devcards.cljs
- src/cljs/athens/devcards/style_guide.cljs
- src/cljs/athens/style.cljs
I see you’re developing devcards in this `design-system` branch. I wasn’t sure how to view these devcards in the browser, so my CSS change in the first commit was made blind. Please add instructions for opening the devcards to `CONTRIBUTING.md` at some point.
In my second commit, I fixed `script/style` and `script/lint`, but I didn’t fix `script/carve` since I’m not sure whether you want to ignore the unused variables (e.g. `OPACITIES`) or wait until code is added that uses them.
> design system: add fallback font and fix some CI test failures

- src/cljc/athens/lib/dom/attributes.cljc
- src/cljs/athens/style.cljs
- test/athens/lib/dom/attributes_test.cljc
@tangjeff0 What do you think about this? It should make combining styles, classes and later other things like event listeners much cleaner (see #111)
I'm thinking about adding specialized key listeners in the same like `:on-keypress {:ESC (fn [event] )}` later. This will help implement #64
> chore: Add with-attributes to clean up attributes

- src/cljs/athens/router.cljs
- Page with title: “Athens vs Roam Tech Stack”
- Page without title: “Athens Research”
- Page with title: “Athens vs Roam Tech Stack – Athens”
- Page without title: “untitled – Athens”
> feat: clearer browser tab titles

- .cljstyle
- test/athens/parser_test.clj
See commit messages for details.
> style: reformat and restructure tests in parser_test.clj

- src/cljc/athens/parser.cljc
- test/athens/parser_test.clj
I replaced `any-chars` with more specific rules and then added tests for those rules. I also added tests for the untested parser rules `block-ref` and `bold`.
I based `url-link-url`’s escaping rules off [CommonMark’s escaping rules for links](https://spec.commonmark.org/0.29/#links). Roam doesn’t implement those escaping rules, but I think they should be implemented. There are some links in the sample database `data/athens.datoms`, e.g. `[Syncope](https://en.wikipedia.org/wiki/Syncope_(medicine))`, that are parsed incorrectly in Roam and are now parsed correctly in Athens.
The uses of `any-chars` I replaced were all of the uses that represented limited, non-generically-formattable text. The remaining uses of `any-chars` in the current parser will need to support recursive formatting such …
> feat(parsing): more accurately parse block-ref, hashtag, and url-link-url

- src/cljc/athens/parser.cljc
- test/athens/parser_test.clj
Allow writing bold-formatted text in a link with `**foo**`, or writing a literal `]` with `\]`.
As the parsing of more formatting syntax such as `~~strikethrough~~` is implemented, this parse rule might need to be updated to accept that syntax as well. Only some of the new syntax will be allowed in link text.
The backslash-escaping was taken from Markdown. Roam doesn’t support that syntax (yet?), but I think Athens should.
[Add `?w=1` to the GitHub diff URL](https://github.com/athensresearch/athens/pull/127/files?w=1) to hide the whitespace-only changes in the second hunk of `src/cljc/athens/parser.cljc`.
> feat(parsing): parse formatting syntax within url-link-text

- src/cljs/athens/devcards/icons.cljs
- Use macro for simpler syntax where possible
- Provide examples of icons styled with design system properties
> refactor(icons): show macro and styling examples in devcard

- src/cljs/athens/devcards/db_boxes.cljs
This PR includes two minor additions to the Datascript explorer based on the feedback from @tomisme and @tangjeff0 in #67:
1. Reverse the flexbox direction of the datascript browse card, so the control box (allowing you to go back to earlier states of the card) is on top.
2. Add reverse references when browsing individual entities: this let's you browse "up" the graph.
As always: any feedback is welcome!
> Improve datascript explorer

- src/cljs/athens/devcards/db_boxes.cljs
More usable database browser results table [Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.db_boxes)
> feat(db-boxes): more usable results table

- src/cljs/athens/devcards/all_pages.cljs
- src/cljs/athens/devcards/athena.cljs
- src/cljs/athens/devcards/blocks.cljs
- src/cljs/athens/devcards/icons.cljs
- src/cljs/athens/devcards/left_sidebar.cljs
- src/cljs/athens/devcards/style_guide.cljs
- src/cljs/athens/style.cljs
- src/cljs/athens/views.cljs
[Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.style_guide)
- New opacity scale `lower low med high higher`
- New function `(color)` to handle colors and opacities without having to think about hex vs. HSL etc.
- Replace all uses of color and opacity with new function and consistent values
TODO: documentation
> Refactor opacity

- src/cljs/athens/devcards/style_guide.cljs
Removes link from style_guide page to icons page, which worked in local development but not in deployed GH Pages.
[Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.style_guide)
> fix(style-guide): remove broken icons link

- src/cljs/athens/devcards/blocks.cljs
- src/cljs/athens/parse_renderer.cljs
Switch to fragments for spans that don't apply styling or have semantic meaning. Makes for easier markup to navigate, and less work for the browser to do.
[Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.blocks)
> refactor(blocks): don't create unnecessary spans

- src/cljs/athens/devcards/all_pages.cljs
- src/cljs/athens/devcards/athena.cljs
- src/cljs/athens/devcards/block_page.cljs
- src/cljs/athens/devcards/blocks.cljs
- src/cljs/athens/devcards/buttons.cljs
- src/cljs/athens/devcards/db_boxes.cljs
- src/cljs/athens/devcards/left_sidebar.cljs
- src/cljs/athens/devcards/node_page.cljs
- src/cljs/athens/devcards/parser.cljs
- src/cljs/athens/devcards/style_guide.cljs
- src/cljs/athens/style.cljs
- src/cljs/athens/views.cljs
Reverts athensresearch/athens#160
Pretty nasty conflicts while trying to rebase onto the tangjeff0/athens komponentit branch at: https://github.com/tangjeff0/athens/commit/cf0a87e6e78e5303b6e962474e8fa129128ee748
Will merge the komponentit branch in even though buggy so we can have a clean starting point for new branches
> Revert "refactor(style): use global styles instead of base styles"

- src/cljs/athens/devcards.cljs
- src/cljs/athens/devcards/breadcrumbs.cljs
[Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.breadcrumbs)
Adds dummy Breadcrumbs component. Breadcrumbs will need to be enhanced with links in order to be usable.
> feat(breadcrumbs): add dummy breadcrumbs component

- project.clj
- src/cljs/athens/coeffects.cljs
- src/cljs/athens/core.cljs
- src/cljs/athens/devcards/athena.cljs
- src/cljs/athens/devcards/blocks.cljs
- src/cljs/athens/effects.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/listeners.cljs
load
- refactor event into coeffects and effects files
- get ride of initial re-frame dispatches in athena and blocks
coeffects is just a stub right now. Can probably make `localStore` its own `cofx` as in https://day8.github.io/re-frame/Coeffects/ once we begin to utilize it more
also, db will eventually maybe want to be stored in IndexedDB down the line
> feat(localStorage): persist db now, no longer need to request GH each

- package.json
- project.clj
- src/cljs/athens/devcards/all_pages.cljs
- yarn.lock
This is my first PR to improve datetime format for `Created` and `Modified` columns, based on the UI showed in #100.
It uses `juxt/tick`, the chosen date library as discussed in the issue.
Some choices I made:
- The am/pm marker is simply put to lower case but this [SO answer](https://stackoverflow.com/questions/13581608/displaying-am-and-pm-in-lower-case-after-date-formatting/13581910#13581910), although not the accepted best answer, says that it is not the correct way to do it in Java with the old `SimpleDateFormat`. I went with it anyway because:
1. Athens runs in the browser so the date input is always AM/PM and thus it doesn't have the problem mentioned in the following SO comment:
> [...] some phones display AM/PM, others display a.m./p.m. 
2. I couldn't find the equivalent of …
> All pages date format

- .github/workflows/build.yml
- project.clj
- script/deploy
- src/cljs/athens/devcards/spinner.cljs
- makes single `run:` commands one-liners
- deploy to GH pages (TODO: document how to configure for local)
- compiles with `shadow-cljs` because faster
- `prn`s the commit version
> auto deploy with CI scripts now

- src/cljs/athens/devcards/blocks.cljs
- src/cljs/athens/parse_renderer.cljs
This one scares me a little because of how much is happening at the highest levels of UI code. This is probably being far too clever and brittle, but I haven't found any actual or theoretical problems yet.
**How it works:**
- Textareas are absolutely positioned over their respective blocks.
- Textareas are invisible and display: none by default.
- Hovering a block enables the textarea so that it can be clicked.
- Interactible elements in blocks are z-indexed above the textarea so they can be clicked.
- Regular text in a block is behind the textarea, so is never clicked.
- Clicks are passed through directly to the textarea so the textarea captures the click location.
- Focusing a textarea makes it opaque and in front, and textareas are also …
> feat(blocks): fancier block editing

- src/cljs/athens/devcards/filters.cljs
- src/cljs/athens/devcards/textinput.cljs
[Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.filters)
- Filters use new input component.
- Added 'no results found' message when list is filtered to zero
> Filters use new input

- src/cljs/athens/devcards/buttons.cljs
- src/cljs/athens/devcards/right_sidebar.cljs
[Demo](https://shanberg.github.io/athens/#/page/AVOHMK6bK)
- Show a nice message when the sidebar is empty
- Sidebar item collapse toggle should rotate when items are open. Fixes #200 
- Sidebar items shouldn't collapse into each other
> fix(Sidebar): readability, usability improvements

- src/cljs/athens/devcards/daily_notes.cljs
- src/cljs/athens/effects.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/views.cljs
https://github.com/tonsky/datascript/issues/315
Many issues here, mainly to do with asynchronous `dispatch`es, routing, and resetting the datascript and re-frame dbs. Not a normal bug, as it's probably rare to reset these two database in an app. My poorly written code elsewhere probably didn't help, namely with routing and me not realizing that resetting app-db would reset the routing as well. But the stack trace for the pull API was incredibly difficult to go through, and the resetting of the DB might've had non-deterministic behavior due to the nature of dispatches? Not sure here, maybe I'm just trying to blame other people.
The code that led to the problem mainly:
```
(defn daily-notes-panel
[]
(let [note-refs (subscribe [:daily-notes])]
(fn []
(when (empty? @note-refs)
(dispatch …
```
> Debug datascript

- src/cljs/athens/db.cljs
- src/cljs/athens/devcards/dropdown.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/parse_renderer.cljs
- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/dropdown.cljs
No longer use `:on-change` for editing text. Instead, capture each `:on-key-down` and let `:on-change` dispatch to re-frame. Slight bugs, but this makes more sense long term because we're going to have custom keybindings.
Lots left to do, but a lot less uncertainty. Much clearer path forward for #97
> feat(blocks): start on slash commands, inline-search, hot keys. refactor devcards and athena

- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/dropdown.cljs
[Demo](https://shanberg.github.io/athens/#/pages)
Slash menu should appear at the bottom-left corner of the textarea in the block being edited. This should be improved later by making it appear at the caret position.
> Menu positioning

- src/cljs/athens/parse_renderer.cljs
- src/cljs/athens/style.cljs
- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/block_page.cljs
- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/dropdown.cljs
- src/cljs/athens/views/node_page.cljs
- src/cljs/athens/views/right_sidebar.cljs
Refactor all our uses of z-index to either be a small numeric value, essentially a "relative" z-index, or a semantic value like ":zindex-modal" or ":zindex-dropdown", drawn from `athens.style`.
Fixes #230
> Refactor zindex

- src/cljs/athens/views/right_sidebar.cljs
[Demo](https://shanberg.github.io/athens/#/)
Sidebar should no longer appear open-ish for a couple frames before hiding itself.
- Refactor sidebar toggling to use regular CSS transitions rather than CSS animation, because of difficulty setting the initial state properly.
- Sidebar should open and close more smoothly now, though it could still be better. Currently it’s using negative margins to slide the content out of the way, and it'd be better if that used a CSS transform, which is allowed to run on the GPU and won't trigger content reflow. That'd be a small optimization though.
> fix(right-sidebar): shouldn't flicker on start

- src/cljs/athens/views/all_pages.cljs
`date-col-format` in `all_pages.cljs` had the format - `"LLLL MM, yyyy h':'mma"` which would yield July 07, 2020 for all dates in July.
This format has been fixed to be `"LLLL dd, yyyy h':'mma"`.
> Fix incorrect date time format

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/listeners.cljs
- src/cljs/athens/views/blocks.cljs
- no longer have "bad vibes" `swap!`s
- use atom listener instead of `on-change` for reagent updates
- use :edit/time for datascript updates
> feat(blocks): first start on (()) and [[]] search

- src/cljs/athens/views/blocks.cljs
[Demo](shanberg.github.io/athens/)
Cleaner dragging style
Also (finally) fixes links-appearing-over-hovered-textarea issue.
> Restyle dragging

- src/cljc/athens/parser.cljc
- src/cljs/athens/parse_renderer.cljs
- src/cljs/athens/views/blocks.cljs
(This is my first pull request, so if I'm doing anything wrong style-wise don't hesitate to let me know!)
* the parser now correctly identifies nested page links and multiple page links in one block. For example:
```
user=> (athens.parser/parse-to-ast "[[Hello [[Bruh]] ]] [[World]]")
[:block [:page-link "Hello " [:page-link "Bruh"] " "] " " [:page-link "World"]]
```
* non-existent pages linked in blocks would now be automatically created (including multiple nested pages!).
Partially fixes #5 
* nested page rendering currenty doesn't work. We need to fix the front-end to make it look like Roam.
* if the user deletes the references to empty pages, these pages won't disappear automatically. We can survey the database and delete anything without references and without block content (i.e. …
> fix(parser, blocks): fixed incorrect parser outputs and added non-existent pages auto-create 

- src/cljc/athens/util.cljc
- src/cljs/athens/events.cljs
- src/cljs/athens/views/left_sidebar.cljs
TODO
- refactor `left-sidebar-drop-above` and `left-sidebar-drop-below` after finding more examples of dnd (i.e. with blocks and right sidebar)
- upgrade to datascript 1.0.0 so we don't need `(map-order)` and `(map-shortcuts)`
> feat(left-sidebar): drag and drop, re-order shortcuts

- src/cljs/athens/style.cljs
- src/cljs/athens/views/all_pages.cljs
- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/left_sidebar.cljs
- src/cljs/athens/views/node_page.cljs
- src/cljs/athens/views/right_sidebar.cljs
Minor polish around a few corners of the app, just sweeping up little stuff.
- Left sidebar toggles smoothly
- Unified `kbd` element style
- Improved style for help text in empty right sidebar
- Improved node page title alignment
- Improved spacing around all-pages table
> Minor polish

- src/cljs/athens/events.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/blocks.cljs
- Pressing escape closes slash menus, block/page search menus, and ends block editing, in that order.
> feat(blocks): esc to close menus and stop editing

- src/cljs/athens/views/buttons.cljs
- src/cljs/athens/views/dropdown.cljs
- src/cljs/athens/views/node_page.cljs
[Demo](https://shanberg.github.io/athens)
Adds dropdown menu with some placeholder page controls: add to bookmarks and delete.
> feat(page): block in page menu

- src/cljs/athens/devcards/app_toolbar.cljs
- src/cljs/athens/views/modal.cljs
Adds modal, attached to the 'import' toolbar button to show some intro/help text before users add data to Athens from elsewhere.
> feat(import): add modal gate for import flow

- src/cljs/athens/views/blocks.cljs
Restyled block selections to better separate selected siblings.
> feat(blocks): polished selected blocks

- src/cljs/athens/views/athena.cljs
- Better alignment for search results in Athena
- Replaced default input clear button with custom clear button
> feat(athena): polished results and close button

- src/cljs/athens/style.cljs
[Demo](https://shanberg.github.io/athens)
Use the browser's :focus-visible pseudo-class to only show a focus highlight when the user's using the keyboard, e.g. when they're tabbing through buttons and form elements. Hide the focus highlight otherwise.
> feat(style): only show focus ring if using keyboard

- src/cljc/athens/util.cljc
- src/cljs/athens/views/athena.cljs
This PR closes #271 and checks off part of #126 
Athena can now scroll through the search results with arrow keys. The implementation also cycles through the search result list.
> feat(athena): scroll search results with arrow keys

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/style.cljs
- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/buttons.cljs
- src/cljs/athens/views/dropdown.cljs
- src/cljs/athens/views/node_page.cljs
Branches off of @shanberg 's #272, so also implements shortcut add/remove
> refactor(dropdown): use styles instead of thin wrappers -- page menu, inline search, and slash commands

- src/cljs/athens/parse_renderer.cljs
- src/cljs/athens/views/node_page.cljs
* Empty pages auto-created from links can now be edited
* Clicking on titles for linked references can now navigate to the page
* Clikcing on page links will not drop to editing view now
_Note: upstream `devcard/dropdown` is broken, so currently building would fail, but the changes work on my local machine (after deleting `devcard/dropdown`). Sorry for no demo :)_
> fix(pages): various improvements to pages

- src/cljs/athens/views/athena.cljs
This closes #299 by dispatching the `:athena/toggle` event when the user clicks on a search result.
> fix(athena): close the athena menu when navigating to a page via click

- src/cljs/athens/db.cljs
- src/cljs/athens/util.cljs
- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/node_page.cljs
This PR closes #301 
* create util function for escaping all regexp special characters in a given string
* escape the title in Linked and Unlinked references.
* escape the query in re-case-insensitive
Co-authored-by: nthd3gr33
> fix(athena): escape special chars in search input and title

- src/cljs/athens/devcards/dropdown.cljs
`devcards/dropdown.cljs` was referring to components in `view/dropdown.cljs` that either don't exist anymore or have been commented out. This led to broken deploys at the `Compile App and Devcards` step.
This PR fixes the broken deploy by commenting out the offending functions in `devcards/dropdown.cljs`.
> fix(devcards): broken devcards deploy

- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/blocks.cljs
This PR closes #298 
The slash commands list can now scroll through the search results with arrow keys. The implementation also cycles through the search result list.
https://www.loom.com/share/db88315bda8d4b78a90fa3315cd94888
> feat(slash commands): scroll slash commands with arrow keys 

- src/cljs/athens/db.cljs
- src/cljs/athens/util.cljs
- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/node_page.cljs
Reference: <https://github.com/athensresearch/athens/pull/297#discussion_r461228254>
I was hesitate to move helper functions to `db` (temporarily) than `util` because I didn't want the `db` file to get too large and unmaintainable, but it turned out that `db` is a more logical place in terms of common sense and namespace references - because `db` imports `util`, putting the helper functions in `util` results in circular references.
I'll keep in mind to split it out in the future when more counting, query, and graph features are implemented, and sorry @tangjeff0 for this inconvenience.
> fix: re-positioned page reference helper functions to a more logical place

- src/cljs/athens/components.cljs
- src/cljs/athens/views/blocks.cljs
- Styles checkboxes, code, and embeds in blocks
- Adjusts styles to hovered blocks to improve consistency. Hovered background color is `background-minus-1`
- Adds block-editing toggle button behind blocks to increase the clickable area, especially for media blocks where the media fills the block-content area.
- Adds a wrapper to properly size things like video and maps embeds in a responsive container to fill available space while maintaining a 16:9 aspect ratio.
> feat(blocks): style new components

- src/cljs/athens/db.cljs
- src/cljs/athens/views/athena.cljs
Refactor the `search-in-node-title` and `search-in-block-content` functions to return only 20 items by default. This should fix #269.
* These functions also now take an optional parameter to specify max number of results
* Remove (take 20) from create-search-handler since those functions default to returning 20 results
Advantage of this refactor is that we can exert more control over these functions by specifying the maximum number of results returned by these functions.
There is still some latency when the search query is 1 or 2 characters long but the search functions do not hang anymore.
> refactor: search functions

- CONTRIBUTING.md
- GOVERNANCE.md
Are these instructions for getting started clearer? Will probably delete [README column of Project Board](https://github.com/athensresearch/athens/projects/2#column-9464291), then link to CONTRIBUTING from Top of "Good First Issues" column.
This doesn't include the resources for developers. It assumes that link to ClojureFam is a good entrypoint for learning.
@bonobo-d
> docs: update CONTRIBUTING with better starting instructions. update community roles

- shadow-cljs.edn
The local cljs repl is broken after updating `shadow-cljs` to `2.8.110`. This PR fixes that issue by removing the offending `:repl-init-ns` option.
Reference - https://github.com/thheller/shadow-cljs/issues/700#issuecomment-623991281
> Fix cljs repl issue by removing the :repl-init-ns option

- .gitignore
- src/cljs/athens/db.cljs
- src/cljs/athens/keybindings.cljs
(This PR is mostly for learning. If you think it is out of place/unnecessary, I don't mind closing it. I learned a lot anyway)
1. Fix error when trying to type any character within `[[]]` or `(())` (closes #315 )
2. Even after fixing the above, the block search function hangs the whole app when entering the first character within `(())` (perhaps because there are too many results?) This is a deeper issue to be investigated, but as a temporary workaround I have turned off `db/search-in-block-content`'s behavior for queries shorter than 4 characters. This way we can at least test the other behavior.
- ![ROdZcWLH2F](https://user-images.githubusercontent.com/66203865/89115371-9793a100-d4c2-11ea-9ec8-9bcdb89034ce.gif)
3. Refactored query/results updating into its own function to make it a bit …
> Inline search fixes

- .carve_ignore
- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/listeners.cljs
- src/cljs/athens/views/blocks.cljs
- close #329 
- handles #330 partly, but need to fix selection bugs: better drag to select and (avoid redundant selection), figure out how to reindex the blocks after deleted blocks. also need more work for copy/cut/paste for nested blocks
- inline ctrl-z works inline as well now, but there will be collisions on MacOS I believe with global datascript undo/redo
> feat(blocks): copy, cut, paste for inline textarea

- CONTRIBUTING.md
It took me some time to start using the correct namespace in the REPL and clearly I was missing out. Adding it to `CONTRIBUTING.md` might help some people out.
> Add instructions to set namespace for CIDER to CONTRIBUTING.md

- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/blocks.cljs
I'm proposing a way to fix #340. Now all functions that auto-generate text (auto-pairing, auto-complete, enter, etc.) in keybindings.cljs write to a new atom parameter `:generated-str` instead of directly to `:atom-string`. The job of writing to `:atom-string` is left to `blocks/block-on-change` instead. `blocks/block-on-change` now has some logic to switch between auto-generated text and event text from `on-change`.
This seems to fix all behavior I've tested (auto-completion, auto-pairing, copy&paste), but it does feel a bit hacky. Without a deeper understanding of the direction we want to take I can't come up with a better solution right now.
> Proposed fix to on-change conflict

- src/cljs/athens/events.cljs
- src/cljs/athens/views/node_page.cljs
TODO: prompt to merge pages if renaming title to an existing page. Separate PR.
- Done during ClojureFam Office Hours to demonstrate REPL-driven development. [Video, starts at 43:00](https://www.notion.so/egghead/01-ClojureFam-Office-Hours-16d0d8642f474c18ad3ec8127b1a9cab).
- Differs from the video in that we store old-title a different way. The video grabs the title from the `ref-groups` data structure, but that's not a general solution.
> feat(page): update linked refs when title is updated

- src/cljs/athens/db.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/node_page.cljs
- better naming for strings
`:atom-string` -> `:string/local`
`:generated-str` -> `:string/generated`
`:old-string` -> `:string/previous`
- typeahead for slash commands, expansion fixed with `generated`. closes #327
- lots of docstring comments
- refactor arrow keys, more code reuse by condensing slash commands and inline search menus into generic dropdown
- let backspace use more textarea default behavior
- create second atom listener for `generated`
- organize function order
> rfct(blocks): docs, better naming, code reuse

- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/block_page.cljs
- src/cljs/athens/views/blocks.cljs
- not a complete fix. block-page title should actually have mostly same behavior as normal block textarea: slash commands, inline search, transact on blur, main difference is what happens on `backspace` and `enter`. not finishing in this PR because might take some more design work. see #344 @juniusfree
- rename all textarea event handlers to `textarea-*`
- fix italics happening when user presses `ctrl-shift-i` for devtools
- rewrite `walk-parse-tree-for-link` to use atoms
- no longer rely on `edit-time` for syncing datascript state to local block string state
- can finish #352 now - just add a key for the parser for `block-refs`
> rfct(textarea): use on-blur events for block transactions. refactor walk-parse-tree-for-links

- src/cljs/athens/components.cljs
- src/cljs/athens/parse_renderer.cljs
- fix(page-links): react index error from nested links
- fix(todo): `checked` boolean instead of string value
- fix(todo): on-change instead of on-click
- fix(block-refs): break out of self transclusions to avoid stack overflow. [card](https://github.com/athensresearch/athens/projects/4#card-43628910)
> fix(parser): errors and warnings from TODOS, nested links, self-transclusions

- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/blocks.cljs
- inline search auto-complete without results still moves caret
- typing after "/" without results hides slash menu
- `nth` over `get`
- proper expansion for "/" - remove query characters
- fix backspace bug where bksp with all text highlighted deleted block
- show lower opacity hint when no search results for inline
> fix(inline): slash and search

- src/cljs/athens/events.cljs
- src/cljs/athens/util.cljs
- src/cljs/athens/views/blocks.cljs
- flickering mostly gone
- transition between states smoother
- prevent any drop effect if block/orders wouldn't change, using `no-effect?` condition
- separate and name event handlers: `block-drag-over`, `block-drag-leave`, `block-drop`, `bullet-...`
> fix(dnd): fix several drag n drop bugs. rfct(blocks): decouple evt handlers from hiccup

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/listeners.cljs
- src/cljs/athens/subs.cljs
- src/cljs/athens/util.cljs
- src/cljs/athens/views/blocks.cljs
- fixes #326 for shift+up/down, shift+click, and mousedown+mouseenter
- fixes bug where drag and drop with selected text in textarea crashes app
- UI: comments out `hover` and `is-editing` opacities, to make selected blocks easier
- TODO: some behavior for indent, cut, and backspace when multi-selected blocks (especially indexing, order)
- TODO: reorganize blocks and listeners
> fix(selection): nested opacities for shift+up/down, shift+click, and mousedown+mouseenter

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/listeners.cljs
- currently don't know best way to indent when latter blocks are at a different level in the tree, e.g. https://www.loom.com/share/77e2d4be8fd64fabaf5528fa3d824346
- so only allow multi-block indent if blocks have same parent
- creates pretty gnarly `indent-multi` and `unindent-multi` fns. very ugly but I think there's a better solution down the line so not optimizing for now.
> fix(selection): indent and unindent multiple blocks

- src/cljs/athens/listeners.cljs
- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/node_page.cljs
closes #328
Implemented using Reagent lifecycle methods](https://github.com/reagent-project/reagent/blob/master/doc/CreatingReagentComponents.md) and [refs](https://medium.com/@pitipatdop/little-neat-trick-to-capture-click-outside-react-component-5604830beb7f).
Not using React Hooks but probably could. Haven't using Hooks from Reagent yet but it requires some extra steps, I believe.
Made a weak attempt at a [generic `dropdown` component](https://gist.github.com/tangjeff0/520c1b7d73213fd6053bd45a16e17c20). Form-3 components have a good amount of boilerplate, and the logic for dropdowns is quite similar. Would probably pass these as parameters for a generic dropdown class:
- `handle-click-outside`
- `display-name`
- `component-fn`
> feat: clicking outside closes out of dropdowns

- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/blocks.cljs
When using `:string/generated` instead of `:string/local` for custom keypress behavior, this made it so that user had to press any key one time before it would change the textarea value again. Probably had to do with `:generated-str-listener`.
- `nth` takes an additional parameter when not found. very useful
- `re-matches` returns a vector instead of one value if capture groups are used&found
> fix: get rid of `:string/generated` everywhere. use `nth` with not-found

- src/cljs/athens/views/block_page.cljs
@theianjones the reason why you were getting a linting error in #365 is that the branch was stale. #374 refactors `destruct-e`, so that there is now `destruct-target` and `destruct-key-down`. This PR should fix current build, which was previously using an unresolved symbol.
> fix(block-page): use destruct-key-down instead of destruct-e

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/listeners.cljs
- src/cljs/athens/views/blocks.cljs
- fragments `:drop/bullet` to dispatch other events now
- uses custom functions in `d/q`
> feat(dnd): multi-block works mainly now

- resources/public/index.html
- src/cljs/athens/events.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/daily_notes.cljs
https://github.com/athensresearch/athens/projects/4#card-46358603 and others
- hide re-frame-10x: modifies `index.html` to set `localStorage` directly. probably want to not even bundle re-frame-10x in release app, but don't want to mess w config right now
- daily-notes guard: must check the entities exist before `pull`. I feel like I don't like that default behavior of `posh`/`datascript`
- athena: pressing enter before debounce has finished crashes. probably more elegant solution that still uses debounce but quick solution
> fix: athena, re-frame, daily-notes guard, right-sidebar, bold caret placement

- src/cljs/athens/events.cljs
Block orders get messed up if you hold down enter. Otherwise, will write to fs on each transaction until we start getting performance issues
> feat: auto-save

- src/cljs/athens/views/left_sidebar.cljs
This prevents an extra vertical scrollbar from being displayed at the bottom when opening/closing the left sidebar. There is still a vertical scrollbar displayed when the text is wider than the left sidebar.
Before:
After:
> fix(left-sidebar) extra scrollbar when opening left sidebar

- src/cljs/athens/keybindings.cljs
- src/cljs/athens/listeners.cljs
- src/cljs/athens/util.cljs
`case` doesn't work with enumerators it seems like?
not tested on Windows
> feat(keybindings): use ctrl or meta based on OS (windows/linux/mac)

- package.json
- yarn.lock
People getting `async hooks` error from electron. I'm not sure if this is the problem as it seems to be non-deterministic, but hope it's a quick fix because I've spent a lot of time trying to debug this without results.
> fix(electron): rollback to 9.2 from 9.3

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/keybindings.cljs
Problem was `deepest-child-block` was always being called, but should only be called if previous conditions are not true.
> fix(arrow): stop crashing; refactor next/prev block; round last-row

- src/cljs/athens/views/app_toolbar.cljs
- src/cljs/athens/views/node_page.cljs
> feat(date-page): jump to date from app-toolbar rather than

- src/cljs/athens/effects.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/subs.cljs
- src/cljs/athens/util.cljs
- src/cljs/athens/views/blocks.cljs
Before, editing/uid uses `getElement` which finds an HTML `#element` by tag. However, there can be multiple elements with the same `editing-uid-` HTML id, because a block can show up on the page, under linked references, or in the right sidebar.
https://www.loom.com/share/dd50a1b197ca4f7a851f0204b23d87bb
Now, the DOM filters to find the correct block to move to. TODO: fix linked references so that they act more like block pages than blocks (where pressing enter creates a child instead of a sibling, or don't allow un-indent).
> feat(editing/uid): don't jump around if multiple HTML elements with same block uid

- src/cljs/athens/events.cljs
- fixes bug introduced in https://github.com/tangjeff0/athens/blob/1bdc7647a851692c48e54db4958cd5cd85e72ede/src/cljs/athens/events.cljs#L22-L26
- interestingly, this was detected because global re-frame key-val `:mouse-down` was `nil`, rather than `false`... `false?` is strong!
> fix(re-frame): db->fx didn't update params correctly

- src/cljs/athens/views/block_page.cljs
> fix(ui): hide link filters button for block page

- src/cljs/athens/views/node_page.cljs
Users should be allowed to delete date pages, but temporarily fixes #465.
> fix(ui): don't let user delete timeline page

- src/cljs/athens/views/node_page.cljs
#468 disallowed bookmarks, not delete. only bookmark should be available
> fix(ui): disallow delete, not bookmark

- src/cljs/athens/main/core.cljs
- src/cljs/athens/views/app_toolbar.cljs
- Uses 'hidden inset' titlebar style for more integrated appearance.
- Makes app header a window drag handle
- Fixes missing background color in appheader controls
> feat: hide electron title bar

- src/cljs/athens/electron.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/views/app_toolbar.cljs
- also use `writeFile` instead of `writeFileSync` instead. wasn't using async version before because got  errors, but this was when there was no debounce, meaning the error was almost certainly because multiple  attempts of writing at the same time. this can no longer happen with the async version.
- got a similar error when using pipes. pipes are even better than async, so can eventually go that
> perf(electron): debounce save 15 secs

- src/cljs/athens/views/right_sidebar.cljs
- Truncate page titles in sidebar items to one line.
- Smaller text size for item titles in sidebar
- Remove extra spacing from top of sidebar items
> feat(sidebar): smaller and truncated titles for pages in sidebar

- src/cljs/athens/electron.cljs
- src/cljs/athens/views/app_toolbar.cljs
Previously thought there was an issue with node's `fs.writeFile` because it seemed like it was blocking. In actuality, I had messed up the order for the `update-mtime`. The condition in `sync-db-from-fs` was always true, even when writing to the filesystem. This would cause each write to also trigger a read from the filesystem, when we only want that to happen if, for instance, Dropbox updates the db.
Also use streams, which should reduce memory significantly.
> fix(electron): debounce was "blocking"; perf(electron): use streams

- src/cljs/athens/views/node_page.cljs
fix #464 
I found other issues that might be related to this but I'm not sure if they should be included here.
- arrow down is not working when the cursor is on the top node
- the cursor position is inconsistent when moving up and down the blocks using the arrow key
> fix: missing cursor issue #464

- .github/workflows/build.yml
Changes to the github actions due to github fixing a
security vulnerability:
https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
These were deprecated on 16th Nov 2020:
https://github.blog/changelog/2020-11-09-github-actions-removing-set-env-and-add-path-commands-on-november-16/
The repo for `setup-clj-kondo` has been updated but a new release
version has not be cut yet.
Use master for now but you probably want to use the actual versions once they've been set.
> fix: github actions

- src/cljs/athens/db.cljs
- src/cljs/athens/views/block_page.cljs
- src/cljs/athens/views/node_page.cljs
Fix for #501
Page Title
Block Page Title
> fix: arrow down key function in page title and block page title #501

- src/cljs/athens/keybindings.cljs
;; if caret within [[brackets]] or #[[brackets]], navigate to that page
;; if caret on a #hashtag, navigate to that page
;; if caret within ((uid)), navigate to that uid
;; otherwise zoom into current block
Code for [[]] and # should be refactored to something cleaner.
Uses `blur` to transact, continues pattern of coupling blur with update block, which isn't ideal.
> feat(keybindings): navigate with ctrl-o

- src/cljs/athens/keybindings.cljs
The desired event is triggered, however it is not perfect:
as the block if opened and closed, the editing pointer moves around.
The movement of the pointer should be freezed as an improvement.
> Add ctrl-down and ctrl-up shortcuts to open/close blocks

- src/cljs/athens/keybindings.cljs
Ctrl+left/right does not crash the app anymore.
> fix(#520): ctrl-left and right need to do nothing

- resources/public/index.html
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views.cljs
- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/node_page.cljs
- src/cljs/athens/views/portal.cljs
- Used for slash-menu, inline (keyboard-based)
- Used for context-menu, node-page-menu (click-based)
- Couldn't get it to work with Athena, Input wouldn't focus for some reason. Not sure why
> rfct(dropdown): use react portal for dropdowns

- src/cljc/athens/walk.cljc
- src/cljs/athens/db.cljs
- src/cljs/athens/effects.cljs
- src/cljs/athens/views/blocks.cljs
- test/athens/walk_test.clj
The attribute is still technically `:block/refs`, even though we are creating references to a [[page]], not a block, to follow Roam spec.
First in a series of PRs. Next up:
- Remove unnecessary functions like `old-block-refs-to-tx-data` and `old-page-refs-to-tx-data`. DataScript `d/with` handles cleanup of references.
- Purpose of `old-titles-to-tx-data` is slightly different: remove orphan pages.
> feat(walk): parse and transact for :page/refs

- src/cljc/athens/patterns.cljc
- src/cljs/athens/events.cljs
- src/cljs/athens/views/node_page.cljs
> feat(references): toggle refs, Link and Link All

- src/cljs/athens/effects.cljs
- node/title prior to rename no longer exists! block/uid persists though
> fix(rename-page): can't use node/title for retracting block/refs

- src/cljc/athens/patterns.cljc
- src/cljs/athens/db.cljs
- src/cljs/athens/effects.cljs
- src/cljs/athens/electron.cljs
- src/cljs/athens/views/all_pages.cljs
- src/cljs/athens/views/block_page.cljs
- src/cljs/athens/views/node_page.cljs
- test/athens/patterns_test.clj
- separate linked/unlinked components, unlinked refs now has its own state
- linked refs open by default
- unlinked refs closed by default, does a regex when user tries to open
- query :block/refs for linked references rather than using regex
- introduce `:schema/version`, which attempts to create `:block/refs` links if version is `nil`, then updates to version 1, on `:desktop/boot`
- create link count column, sort All Pages by link count
- no longer retract and assert Welcome page with `:db/retract-athens-pages` and `:db/transact-athens-pages`
- actually transact `athens-datoms` on new db creation (initial start or Create Modal) such that links are transacted to db
- no longer try to go to last page; always go to Daily Notes on start up. Close #558
> feat(refs): linked refs actually found using datalog queries now

- src/cljs/athens/effects.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/listeners.cljs
- src/cljs/athens/views/app_toolbar.cljs
Adds the sync icon again. Green if Athens has finished saving to local filesystem, yellow if not.
User is alerted if sync hasn't finished yet and they are trying to refresh or quit Athens.
> feat(save): prevent exiting or refreshing Athens if not saved

- src/cljs/athens/events.cljs
Holding down backspace when deleting text can enqueue multiple `:backspace` reg-event-fxes. The first will correctly delete and merge the parent blocks, but the next events in the queue will still be processed.
This is a surgical fix that just checks for an invalid parent and fixes #567, but a more heavy-handed approach may be appropriate to handle other unreported edge-cases of event queueing.
> fix(events): Check for stale parent when deleting block (#567)

- src/cljs/athens/athens_datoms.cljs
With the current beta version, it is possible to change database location using settings button at the top right corner. 
For that reason, current welcome page is outdated since it have the following:
> Outdated welcome page

- src/cljs/athens/keybindings.cljs
Simple fix for https://github.com/athensresearch/athens/issues/556 
This disables `command/ctrl+i` from adding `___text___` 
Future updates should re enable with correct behavior `font-style: italic`
> fix(keybindings): Disable ctrl-i from adding underscores to text

- .github/workflows/build.yml
- package.json
- project.clj
- script/compile
- script/deploy
- src/cljs/athens/core.cljs
- yarn.lock
Re-opening #474.
- user can opt-out by putting `sentry`: `off` in localStorage. can give easier opt-out in the future, but Sentry pretty important
> feat(sentry): setup error tracking

- .github/workflows/build.yml
Curious if you know how to interpolate variables from the Windows command line @juniusfree 
In linux/mac it is:
`lein run -m shadow.cljs.devtools.cli --npm compile main renderer --config-merge "{:closure-defines {athens.core/SENTRY_DSN \"${SENTRY_DSN}\"}}"`
For Windows, I tried unsuccessfully to do:
`lein run -m shadow.cljs.devtools.cli --npm compile main renderer --config-merge "{:closure-defines {athens.core/SENTRY_DSN \"%SENTRY_DSN%\"}}"`
> fix(ci): ignore windows Sentry variable

- package.json
this warning is recived when compiling under linux
```
application Linux category is set to default "Utility"  reason=linux.category is not set and cannot map from macOS docs=https://www.electron.build/configuration/linux
```
Adding it as "Office" > https://specifications.freedesktop.org/menu-spec/latest/apa.html
> feat: added  linux "category" office

- src/cljs/athens/electron.cljs
To fix this issue: https://discord.com/channels/708122962422792194/802652338619285594/813943745271300117
The `filename` is `nil` sometimes that's why `re-find` is failing.
This change is so that when the `filename` is nil, `re-find` will use the empty string.
> fix: re-find issue in fs-watch

- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/block_page.cljs
- src/cljs/athens/views/node_page.cljs
close #713 
- Use `<wbr/>` instead of `&#8203;`, which works on Linux.
- Apply to block-page header as well
> fix(title): Empty title and regex in block query

- src/cljs/athens/electron.cljs
There are two race-conditions, that should resolve https://github.com/athensresearch/athens/issues/698.
They are reproducible without an external sync service; but at first-glance are not obvious to spot, because machines are generally very fast and the debounces also helped to distort reality. :)
The first race-condition is using current `(js/Date.)` instead of the actual mtime of the filesystem. If we force a minimum 1 second delay, we can reproduce this conflict every time:
``` clojure
;; athens.electron/write-db
(when copy?
(.. fs (copyFileSync bkp-filepath filepath))
(dispatch [:db/sync])
;; (dispatch [:db/update-mtime (js/Date.)])
(js/setTimeout #(dispatch [:db/update-mtime (js/Date.)]) 1100))
```
By using the actual mtime from the filesystem, we can avoid any race-conditions …
> fix(electron): Avoid race-condition with filesystem mtime

- src/cljc/athens/parser.cljc
- src/cljs/athens/athens_datoms.cljs
- src/cljs/athens/parse_renderer.cljs
- test/athens/parser_test.clj
`mhchem` KaTeX extension activate.
> Mhchem extension

- package.json
- yarn.lock
- should automatically create `darwin-arm64` build which is for M1 Mac.
- #708
resources
- https://github.com/electron-userland/electron-builder/issues/5402#issuecomment-726577487
- https://github.com/electron-userland/electron-builder/issues/5392 
Having some trouble here. Keep on getting `Unrecognized symbol error` seeming to stem from a python file. Tried the `patch-package` approach and error still exists.
To clarify, the problem is with `electron-builder`, not `electron`. There are a few other cross-platform builders for electron that do seem to more up to date.
> chore(electron): update from 9 to 11

- .clj-kondo/config.edn
- src/cljs/athens/events.cljs
- src/cljs/athens/style.cljs
- src/cljs/athens/views/graph_page.cljs
- src/cljs/athens/views/node_page.cljs
- src/cljs/athens/views/right_sidebar.cljs
https://www.loom.com/share/b3f16aa7c4084c69b4f47a0e03f7bf65
I am not seeing a perf issue for my current graph, although if it's leading to a bad ux, I can include it in this one or come back to it later.
Added docs based on community call discussion. I think incrementally adding docs from each pr(where code has been added or modified) is better than out-of-context adding of docs.
> feat(graph): local-graphs and view customization

- src/cljs/athens/views/node_page.cljs
This should be a fix for #696 but it looks like it's fixed.
So I just fixed a related bug:
The problem is that the `Link` button overflows from its container.
Fixed:
In Roam Research:
It looks like there might be a minor design update if Athens follows the one from Roam. Just let me know.
> fix: unlinked reference overflowing content

- package.json
This PR fixes just the package.json config to re-enable ZIP target on Mac builds, which should re-enable auto-update on Mac.
Fixes https://github.com/athensresearch/athens/issues/749
Note: Issue #749 references an error popup, but was originally about auto update on Mac being broken, which this fixes.
#722 appears to reference that same error popup in #749, and is still not fixed.
> fix(electron): issue updating Mac App

- src/cljs/athens/views/blocks.cljs
fix #742
Athens has two button styles. I used the primary button for this.
https://www.figma.com/file/XITWUHZHNJsIbcCsBkOHpZ/Athens-Design-System?node-id=9%3A1
> fix(block-ref): better reference number

- src/cljs/athens/db.cljs
Fixes #728, sorts references by newest note ID instead of oldest ID.
> enhance(linked-refs): sort references by newest first

- src/cljs/athens/components.cljs
- src/cljs/athens/devcards/buttons.cljs
- src/cljs/athens/devcards/icons.cljs
- src/cljs/athens/devcards/textinput.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/alerts.cljs
- src/cljs/athens/views/app_toolbar.cljs
- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/block_page.cljs
- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/devtool.cljs
- src/cljs/athens/views/dropdown.cljs
- src/cljs/athens/views/filesystem.cljs
- src/cljs/athens/views/filters.cljs
- src/cljs/athens/views/graph_page.cljs
- src/cljs/athens/views/node_page.cljs
- src/cljs/athens/views/right_sidebar.cljs
- src/cljs/athens/views/settings_page.cljs
Reduces the bundle size from a total of 6.72MB to 3.45MB (@material-ui/icons shrinks from 3.27MB to 14.35KB).
As proof please see the before/after output of `npx shadow-cljs run shadow.cljs.build-report app athens-app-report.html`:
- [Before 6.72MB](https://drive.google.com/file/d/1RIBAs1gA5KWvkqGUj1Wj4NuRRzbKgSjn/view?usp=sharing)
- [After 3.45MB](https://drive.google.com/file/d/1m5xp2mj1XX_J0hIVWYUWKFExzSYj33H3/view?usp=sharing)
> perf(icons): optimize size of material-ui/icons

- package.json
Fixes #749, fixes #793 due to default ordering resulting in electron-update choosing ARM64 binary on Intel Macs
See comment on #749 describing validation testing performed
> fix(electron): issue updating Mac (Intel, not Silicon)

- src/cljs/athens/views/blocks.cljs
https://www.loom.com/share/3b3d566401eb45a38e8ea63e74c309e2
This issue forced to fix a root issue about how z-index is handled in too many places.  This was well buried inside the hierarchy. In the loom, I tried to explain the logic for z-index, textarea and block interactions and can probably act as a reference. Cut down a good amount of hacky code with this 😌
> fix(blocks): links made clickable, z-index clean up #772

- src/cljs/athens/views/app_toolbar.cljs
- src/cljs/athens/views/node_page.cljs
close https://github.com/athensresearch/athens/issues/592
---
Also fixed the z-index of the toolbar.
Problem:
The toolbar is below the pop-ups. For example, the toolbar is below the block inline search.
Fixed
The toolbar is now above.
> fix: Persistent Pop-up when scrolling

- src/cljs/athens/views.cljs
- src/cljs/athens/views/right_sidebar.cljs
close #805 (somehow?)
I reduce the size of the scrollbar, change its color, and add border-radius.
Not sure if @shanberg will approve this. 😅 Also, not tested in Mac or Linux.
> fix: toolbar overlaps on scrollbar

- src/cljs/athens/util.cljs
Close https://github.com/athensresearch/athens/discussions/827
Close #834 
Code to avoid the HTML error was simpler to write. Keybindings already has too much tech debt so wanna avoid touching it. Sorry @phrohdoh
> fix(athena): make sure element exists before scroll

- .github/workflows/build.yml
- project.clj
- script/test/karma
- test/athens/db_test.cljs
I'd like to add a few Karma tests, so that I can later conveniently
change stuff closer to frontend without breaking it. The function
to search for node by title is a convenient first target (to just get
Karma tests set up and running) - it's simple, and I want to enhance
it a little bit soon.
(In particular, I want to make it a bit more fuzzy - e.g.,
if I search for "kiwi recipes", the page "Summer [[Kiwi]] and [[Melon]]
Recipes" should come up. Currently it does not, probably because it
does not ignore the `[[` / `]]`.)
> test(db): add Karma test for node search by title

- CONTRIBUTING.md
- resources/public/index.html
close #900
By default, `index.html` creates DOM elements for 10x. But then `athens.style` hides `10x` via CSS. User can then toggle with `ctrl` or `cmd-t`.
Normal 10x behavior is not great. It shows shows, even when it should be closed, when a user resizes the window quickly. Therefore we use inline CSS to toggle.
Also, normal 10x behavior is to use `ctrl-h`, but this can get caught when a user is focused on a textarea. Using `ctrl-t` works more consistently.
> fix(10x): ctrl/cmd-t always works to toggle 10x

- .carve_ignore
- src/cljc/athens/patterns.cljc
- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/views/app_toolbar.cljs
- src/cljs/athens/views/filesystem.cljs
close #561
```
(/ 3736 3842) 97% clean
(-> (- 1056 2)
(+ (- 3088 406))))
1056 pages, 2 shared
3088 pages, 406 shared
3736 math, 3842 actual count
```
When importing a Roam DB that has 3842 pages, 3736 are created in an Athens DB. This could be an error on either Athens's (lossy import) or Roam's side (orphan pages). It's not necessarily lossy.
Import is done by analyzing each `:block/string` for [[links]] and #tags, rather than using datascript values directly. This is because datascript references such as `:block/refs` point to entity ids, which may collide with Athens entity ids.
By looking at plain `:block/string`, it should be easy to reuse the code for markdown import.
> feat: import from Roam

- src/cljs/athens/views/blocks.cljs
Fix #798
- sets 'outline: none' style on the block textarea regardless of is-editing status, to fix case where .is-editing was set after a short delay
> fix-border-flash-on-new-block

- src/cljs/athens/views/athena.cljs
#797
- set Athena max-width to just under 100%
- reflow the results heading when there's not enough space for all contents
> fix: athena should stay within viewport bounds

- src/cljs/athens/views/app_toolbar.cljs
The function syntax for generating the background color was wrong. Simple fix.
> fix: add missing toolbar background color

- src/cljs/athens/views/blocks.cljs
- src/cljs/athens/views/node_page.cljs
fix #819
**Problem:** The `uid` that is passed to `todo-on-click` is the updated one from `recursively-modify-block-for-embed`. Which means it won't be found when `db/get-block` is called.
**Solution:** Use the `original-uid`, if available, or `uid` if not.
I have a question though. Will the `uid` from `recursively-modify-block-for-embed` be used in `parse-and-render`?
---
~~This other issue is not included here. I'll investigate further. https://github.com/athensresearch/athens/issues/819#issuecomment-811677701~~
Also fixes this comment https://github.com/athensresearch/athens/issues/819#issuecomment-811677701
**Problem:** The `uid` of the nested blocked is passed to `parse-and-render` instead of the `uid` of the parent block
**Solution:** Update the `uid` using the `uid` of the parent …
> fix: Checking a TODO item in block embed results to error

- src/cljs/athens/views/block_page.cljs
> fix: non-formatted breadcrumb on page block

- src/cljs/athens/db.cljs
- src/cljs/athens/keybindings.cljs
- src/cljs/athens/views/athena.cljs
Addresses #969 without addressing root problem, using debounce. Wanted to debounce inline ((block-ref)) search as well but query-fn on line 133 of athens.keybindings always returned `nil`.
> perf(athena): debounce athena search

- src/cljs/athens/views/block_page.cljs
**Current behavior:** See https://github.com/athensresearch/athens/pull/972#issuecomment-820496888
**Expected behavior:** When clicking the parsed block reference or page reference on the breadcrumb, Athens should navigate to the block page only
**Solution**: Add an invisible element above the parsed content to prevent it from getting clicked.
> fix: expand the breadcrumb when [[link]], don't navigate

- src/cljs/athens/effects.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/views/right_sidebar.cljs
> fix(right-sidebar): scroll to top if open another page on right

- src/cljs/athens/events.cljs
fix #987 
**Current Behavior:** Given a deleted block/s (deleted by selection ie. the selection is indicated with blue highlight), when the user tries to undo the action, nothing happens.
**Expected Behavior:** Given a deleted block/s (deleted by selection ie. the selection is indicated with blue highlight), when the user tries to undo the action, the deleted block/s should be brought back.
**Problem:** The value of `:editing/uid` is the `uid` of the deleted block (or one of the deleted blocks if multiple blocks are deleted) which makes Athens "freeze" (I'm not sure what's the right word here). Undo for deleted blocks actually works when you click anywhere on Athens before trying to undo.
**Solution:** Update the `:editing/uid` to `nil` after deleting the selected blocks so the system …
> fix: Delete a block and "undo" cannot bring it back

- yarn.lock
https://github.com/athensresearch/athens/runs/2404564505?check_suite_focus=true
GitHub CI says 
```
error Your lockfile needs to be updated, but yarn was run with `--frozen-lockfile`
```
> chore(yarn.lock): electron 11->12 needs new yarn.lock

- src/cljs/athens/views/filesystem.cljs
I recently pushed up some changes to the filesystem dialog and those changes inadvertently caused the "choose file" button in the import-from-roam dialog to be hidden.
This should fix that.
> fix: ensure choose file input is visible in merge from roam dialog

- src/cljs/athens/style.cljs
- src/cljs/athens/views/blocks/bullet.cljs
- src/cljs/athens/views/blocks/core.cljs
- src/cljs/athens/views/blocks/toggle.cljs
- This PR includes changes to the base light theme
- Slightly darker base background color(!)
- Improved color scaling from base background to lighter backgrounds
- Addresses Improved visual indication of hover of bullets and toggles #1016
- Slightly more clickable area given to block bullets
- Note: highlight is slightly larger than actual mouseable area
> feat(blocks): improved visibility of hover/focus of block bullets

- src/cljs/athens/views/buttons.cljs
- src/cljs/athens/views/pages/node_page.cljs
- src/cljs/athens/views/textinput.cljs
- Replace dropdown code with MUI Popover component for improved behavior and control
- Duplicates some dropdown styles, scoped to the node-page. These styles should be moved back up to the main dropdown styles once this work is replicated across the app
- Very small change to button active style, to reduce button attention-gettingness when dropdown open
> rfct(node-page): replace nodepage dropdown with popover

- src/cljs/athens/electron.cljs
**Current behavior:** When dev athens is launched for the first time, an `index.transit` file is created, overwriting the existing `index.transit` created by the production athens app.
**Expected behavior:** If dev athens is launched and does not have a filepath in local storage, it should check for the `index.transit` file at the default location
**Problem:** Dev athens and production athens use different instances of chromium, so they have different localstorages. App startup assumes that if there is no filepath in localstorage, it is absolutely the first time athens has been run, so it creates a new database at the default location, overwriting the existing database.
**Solution:** At startup, check for an `index.transit` file at the default location before creating a new database.
> fix: use index.transit file if already exists

- src/cljs/athens/views/breadcrumbs.cljs
- src/cljs/athens/views/pages/block_page.cljs
- Make all breadcrumbs inherit their text size, and have no margin or padding #1014 
- Minor refactor of breadcrumb styling to remove excess DOM elements
> fix(breadcrumbs): limit breadcrumb size

- src/cljs/athens/components.cljs
Expected Outcome: Given a block embed, when the user deleted the referred block, then the block embed should display the `uid`.
Current Outcome: ...the block embed uid becomes `invalid`
Problem: The block embed is set to show `invalid`
Solution: Show the `content` instead of invalid
Not solved yet: Users need to refresh or re-edit the block-embed to re-render it.
> fix: when block-embed is deleted, replace with content instead of "invalid"

- src/cljs/athens/views/pages/node_page.cljs
fix #1022 (reported in v1.0.0-beta.74, reproduced in v1.0.0-beta.78 as well)
expected outcome: Given a page, when the user deletes it, then Athens should re-direct to the list of pages
current outcome: ...Athens re-directs to 404
1. For daily notes page
Problems: No re-direct to the list of pages
Solution: Ensure that Athens will navigate to the list of pages of deleting a page
2. For non-daily notes page
Problem: `state` is passed to `menu-dropdown` instead of `daily-note?` as a 2nd argument which makes the check for `daily-note?` always true.
Solution: Remove the `state` argument
> fix: Removal of a daily journal page creates a 404

- src/cljs/athens/devcards/blocks.cljs
- src/cljs/athens/devcards/parser.cljs
- src/cljs/athens/views/pages/all_pages.cljs
close #669 
This is a minimal implementation of the feature.
1.  Show a triangle icon just before or after the column header that is actively sorted by. The icon should represent the current sorting direction: :small_red_triangle: :small_red_triangle_down: 
No triangle is visible in other columns.
2. Store `sorted-by` and `growing?` state into re-frame layer instead of local ratoms. So that the sorting preferences are maintained when the user is leaving "All pages" then coming back to it.
> enhance(all-pages): allow sort by titles / links / times

- src/cljs/athens/views/left_sidebar.cljs
Clicking on the logo in the left sidebar will go to https://github.com/athensresearch/athens/issues/new/choose rather than https://github.com/athensresearch/athens/ allowing for the user to more easily be able to create a bug report. 
Idea from https://discord.com/channels/708122962422792194/708122962905006203/840610093438730252. Thanks to @seekanddefine
> enhance(left-sidebar): clicking on the logo opens to issue creation rather than main repo

- src/cljs/athens/views/pages/daily_notes.cljs
Simplified from https://github.com/athensresearch/athens/pull/1061.
https://github.com/athensresearch/athens/pull/1061 also made the loading start before the user scrolls to the very bottom, but @tangjeff0 asked to just reduce the debounce timer for now.
> enhance(daily-notes): Shorter debounce time for loading of daily pages

- .github/workflows/build.yml
- project.clj
- script/style
Downloading cljstyle binary and running it takes just **11s** in GH actions.
Running the style job with `lein cljstyle` takes **30s** when the deps are already cached:
https://github.com/Em-AK/athens/actions/runs/825896007
I let you judge if this is a blocker.
> ci: cache cljstyle and add alias to lein

- src/cljs/athens/views/blocks/textarea_keydown.cljs
close #1004 
close #1127
Thank you for looking into this @kamalmarhubi and @ssjoleary. 
Undo/redo isn't exactly intuitive from a code perspective. Let me walk through what is happening for future reference.
To recap:
- Undo is `ctrl-z` on Linux and Windows, `cmd-z` on Mac.
- Redo is `cmd-shift-z` on Linux and Windows, `cmd-shift-z` on Mac.
There are two cases:
1. User hits undo/redo when not focused on a block 
1. User hits undo/redo in a block
Focus is mapped towards or re-frame key `:editing/uid`. `:editing/uid` does a lot inside Athens, and should probably be documented thoroughly eventually. Right now the important part is how keybindings are handled with respect to it.
This is defined in `listeners.cljs` because global DOM key events must be listened to. If there is no block in focus …
> fix(keybindings): destructive undo/redo on mac/windows

- src/cljs/athens/views/blocks/content.cljs
close #1131 by setting the default line-height on contentarea to 0. 
close #613 (duplicate)
> fix(contentarea): hide multiline text in contentarea

- src/cljs/athens/views/blocks/textarea_keydown.cljs
This fixes #559.
The problem seems to be that the textarea value is set via `(set! (.-value target) new-value)`. This corresponds to `target.value = new-value` in JavaScript and seems to break the undo mechanism.
In the above fix I replaced these commands by calls to `execCommand`, as it is already the case in [surround-and-set](https://sourcegraph.com/github.com/athensresearch/athens@a11ea7b/-/blob/src/cljs/athens/views/blocks/textarea_keydown.cljs?subtree=true#L444:7), which is called when the user presses cmd+y etc. to surround text with `~~`.
> fix(undo): undo after pair character input

- src/cljs/athens/views/pages/node_page.cljs
This fixes #1177 (sticky unlinked references).
It basically adds another atom to the local state of the component to keep track of changes of the block UID, and when they occur, it resets the local state.
However, it might be worth considering to move the block or page state from an atom into `app-db`, although I'm not sure how this might work exactly, since more than one instance of the block/page component can be present (which makes global state hard to use).
> fix(unlinked refs): update unlinked refs when page changes

- src/cljs/athens/db.cljs
- src/cljs/athens/views/athena.cljs
Making search instantaneous. From ~300ms to ~50ms (or less) on my PC . Tested in relatively large db https://roamresearch.com/#/app/KJV/page/lFeHFy8qE
fix #756
> perf(search): faster search for (()), [[]] and ctrl-k

- .github/workflows/build.yml
- project.clj
Issue with re-frame-10x on web :app build
Screenshot:
Screenshot on local (which has more error logs):
[Brought up by @shanberg ](https://discord.com/channels/708122962422792194/802652338619285594/847647941623676958)
The error comes from re-highlight. @neotyk updated a lot of deps including re-frame-10x at https://github.com/athensresearch/athens/commit/181ad52286d982586a9c1f5016d37553915b6b05
Version goes from 0.6.0 to 1.0.2
re-frame-10x changelog switches to re-highlight at 1.0.2 https://github.com/day8/re-frame-10x/blob/master/CHANGELOG.md#102---2021-03-23
Commenting out `deps-check` for now so that athensresearch.github.io/athens works again (and embedded demo on athensresarch.org)
> chore: downgrade re-frame-10x so web version works, comment out deps-check

- package.json
- project.clj
- yarn.lock
close #1245
What this commit does:
- make sure `shadow-cljs` has same version for yarn (package.json) and lein (project.clj)
- make sure we are using `react17`/`react-dom17`, which is required by `reagent1.0.0`
- use latest `re-frame-10x` again
- update `highlight.js` from 9 to 10
- run `yarn upgrade`
Also:
- Add `app` to builds so website is always built/compiled/released if renderer is
- Mirror `yarn` and `lein` commands, see https://github.com/athensresearch/athens/pull/1229#discussion_r640692486 cc @arkRedM 
General problems:
- It's possible for lein and yarn dependencies to get out of sync. e.g. could have 2.10.1 for yarn and 2.11.1 for lein - [source](https://github.com/thheller/shadow-cljs/issues/734#issuecomment-702050391)
- Some of our yarn dependencies have `^`, some don't. `^` …
> chore: upgrade yarn deps alongside lein deps

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/util.cljs
- src/cljs/athens/views/blocks/content.cljs
- src/cljs/athens/views/blocks/core.cljs
- src/cljs/athens/views/devtool.cljs
Fixes for #1267 #1265
Manage selection behaviour with set theory.
`athens.events/select-{up,down}` are working properly, so for now leaving them untouched.
They'll be on a workbench soon with common-events.
> fix(selection): Selection "freeze"

- src/cljs/athens/util.cljs
- src/cljs/athens/views/blocks/content.cljs
- src/cljs/athens/views/blocks/textarea_keydown.cljs
Followup on #1273 .
Turns out that prod build mangles `dataset` access.
Changed all usages of `dataset` to `.getAttribute` which is safe and working.
> fix(selection): prod build mangles dataset access

- src/cljs/athens/views/pages/settings.cljs
Replace "AutoSave" with "Backup" to better indicate we're creating new backup files, and that changes are saved immediately., to partially address #1255
> enhance(settings): clarify language around autosave backups

- src/cljs/athens/views/blocks/textarea_keydown.cljs
This can be seen as an amendment to #1219, since I seem to have overlooked some occurrences of the evil `(swap! state assoc :string/local new-value)`.
This fixes #1250 on my machine.
> fix(cursor pos, undo, #1250) on shift+enter, cmd+enter, pair character removal

- src/cljs/athens/views/athena.cljs
Currently Athena only respects Shift modifier as "open in sidebar" with Enter key, not with left click.
Tested:
* Shift-Enter
* Shift-LeftClick
Not implementing this for new pages yet, because dispatching the open effect for them needs to be delayed until db is updated, and that'd make the code a bit messier.
> feat(athena): Shift+Click opens in right sidebar, not just Shift+Enter

- src/cljs/athens/views/blocks/textarea_keydown.cljs
Fixes #1277. `(re-pattern "invalid-pattern")` throws errors and Athens wouldn't handle those, prompting the user with javascript alerts.
> fix(#1277): compare string without dangerous regex injection for slash cmd

- src/cljs/athens/athens_datoms.cljs
On the "Welcome" Page, currently the documented "open all-pages view" keybinding overlaps with "open graph view" keybinding . The proper keybinding appears to be "alt-a".
> doc: fix "open all-pages" keybinding on Welcome

- src/cljs/athens/athens_datoms.cljs
1. added cmd commands along with ctrl because what ctrl in linux/windows
is cmd in mac
2. Fixed block id for open right sidebar, it was same as id for open
settings page
This fixes #824 and #716
> doc: add mac keybindings for welcome page

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/listeners.cljs
- src/cljs/athens/subs.cljs
- src/cljs/athens/views/blocks/content.cljs
Mouse selection also deselects. Fix #1279
Original block order is preserved when Copy or Cut.
> Selection fixes.

- src/clj/athens/self_hosted/clients.clj
- src/clj/athens/self_hosted/components/web.clj
- src/clj/athens/self_hosted/web/presence.clj
- src/cljc/athens/common_events.cljc
- src/cljc/athens/common_events/schema.cljc
- src/cljs/athens/self_hosted/presence/events.cljs
Logs event itself when schema validation fails.
Confirm `:presence/editing` event.
Use plain keywords (instead of namespaced ones) in `:event/args`.
Broadcast new username when new player joins.
Logs when handler doesn't return handle status event.
> Fix: presence bugs, the easy ones

- src/cljs/athens/events.cljs
- src/cljs/athens/events/remote.cljs
- src/cljs/athens/router.cljs
- src/cljs/athens/views/pages/core.cljs
- src/cljs/athens/views/pages/daily_notes.cljs
fixes #1492
From the issue:
Additional check:
> fix: problems in the daily page scroll

- src/cljc/athens/common_db.cljc
- src/cljc/athens/common_events/resolver.cljc
- src/cljc/athens/common_events/schema.cljc
- src/cljc/athens/patterns.cljc
- test/athens/common_events/block_test.clj
> feat: replace block refs with content

- nginx.conf
Configured timeouts for proxy so it doesn't tread WebSocket connections as normal short lived HTTP connections.
> Fix: RTC timeout in docker-compose setup

- src/clj/athens/self_hosted/web/presence.clj
- src/cljc/athens/common_events.cljc
- src/cljc/athens/common_events/schema.cljc
- src/cljs/athens/self_hosted/client.cljs
- src/cljs/athens/self_hosted/presence/events.cljs
- src/cljs/athens/self_hosted/presence/fx.cljs
- src/cljs/athens/views/pages/settings.cljs
- This PR fixes #1514.
- This will now allow the username to be updated to every client in the lan-party when one of the clients updated the user name.
- A new event to send the new user is created in the presence module on the client-side. This event will be triggered when the username on the settings page is updated.
- A new event is added on the server-side to broadcast the new user name.
- On the server-side, the atom, `athens.self-hosted.clients/clients` is also updated when the user name is changed. This is to ensure that the newly connected clients will get the latest list of user names.
- ~~On the server-side, I'm also thinking if the `editing-handler` and `username-handler` can be generalized but I'm unsure yet on how to do it.~~
> fix: broadcast username on update

- src/clj/athens/self_hosted/web/datascript.clj
Resolution on backend used to happen concurrently, not it don't.
> Fix: concurrent resolution should not happen.

- src/cljs/athens/self_hosted/presence/views.cljs
- src/cljs/athens/views/blocks/content.cljs
- src/cljs/athens/views/blocks/core.cljs
- src/js/components/Avatar/Avatar.tsx
- src/js/components/PresenceDetails/PresenceDetails.tsx
Goal
- Multiple avatars per block
- Removes 'locked' properties from block elements
Changes
- Avatar stacks can limit the number of avatars they show, with the overflow displayed as (+N) avatar
- Avatar stacks can reverse the direction of avatar overlap
- Avatars on blocks wrapped in stack
- Block elements no longer change color based on current presence
> feat(presence): ui support for multiple presence

- src/cljs/athens/core.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/style.cljs
- src/cljs/athens/util.cljs
- src/cljs/athens/views.cljs
- src/cljs/athens/views/app_toolbar.cljs
- src/js/components/concept/AppToolbar/components/WindowButtons.tsx
- src/js/components/utils/style/style.ts
Replaces the core styles with the new one from the TS library. Not a complete changeover yet but a unit of work.
Should appear exactly the same, except in the Presence menu where this change fixes some visual bugs.
- Removes cljs base style inclusions (style variables, html and body styles, etc.), replacing them with TS equivalents.
- Slightly changes the way the theme colors are applied to the DOM, mostly moving it into a classname applied near the root.
- app-toolbar still subscribes to the theme, because it’s using an older form of styling that isn't able to respond to classes on higher components. Everything else just inherits the current theme from the DOM.
Considerations for later:
- Refactor out the `color` function to eliminate the code duplication between the remaining CLJ styles …
> Update style variables

- src/cljs/athens/electron/db_menu/db_list_item.cljs
Just tweaks the style for the buttons so they're not so unsightly. Refactor coming next, but this is simple low-impact fix.
> fix(db menu): less broken style for db picker menu

- src/cljc/athens/common_db.cljc
- src/cljs/athens/views/pages/all_pages.cljs
Fixes #1638 
Changes:
1. Removed the "Body" column because it's the main cause of the slow performance. But @shanberg needs to look at this. 🕶
2. Moved the query fn to `common-db`
3. Removed the `preview-body` fn because it's not needed
> fix: all pages is slow when a page has 100+ blocks

- CHANGELOG.md
- package.json
Needed to manually update `package.json` version to catchup with wrongly executed releases.
> Chore: Release RTC next version

- src/cljs/athens/db.cljs
In addition to fixing the error, it also sorts the references by date added. This is the same behavior as with linked references.  
Close #1680
> fix(block-references) #1680 block reference counter not opening

- src/cljs/athens/components.cljs
Adds a bit of padding to the block embed view 
close #1328
close #817
> fix(block_embed): text overlaps the edit button

- src/cljs/athens/views/blocks/core.cljs
- src/cljs/athens/views/blocks/toggle.cljs
- Hides block toggle and tree indicator (line odwn the left side) until hover or focus within a block
> improvement(blocks): hide block toggle unless interacting

- src/cljs/athens/views.cljs
- src/js/components/AppToolbar/AppToolbar.tsx
- src/js/components/utils/style/style.ts
- Ensures the app toolbar doesn't break out of base layout containment
To test:
- Open presence menu, see that it isn't clipped by the apptoolbar
- Open a dialog (like merge from roam) and see the dimming backdrop properly covers the whole screen, including the app toolbar
> fix(presence): presence menu appears over toolbar

- src/cljs/athens/db.cljs
- src/cljs/athens/style.cljs
- src/cljs/athens/views/app_toolbar.cljs
- src/js/components/AppToolbar/AppToolbar.tsx
- src/js/components/Button/Button.tsx
- src/js/components/utils/useFocusRingEl.tsx
- App toolbar should _not_ zoom when the content zooms
- Default zoom level is 0, not 1. Zooming levels are deltas from the baseline, which is zero
- Removes extra console logs
- Makes unnecessary button props optional
To test:
- Use cmd/ctrl+ to zoom in, cmd/ctrl- to zoom out. Content should change size, but toolbar should not.
- Default zoom level should make things appear smaller than in recent builds
> fix(apptoolbar): unzoom toolbar, correct default zoom

- README.md
The links were stale - pointing to athens-research.ghost.io.
I've updated them to athensresearch.ghost.io
> FIXED: Blog links to Athens Research in README

- src/cljc/athens/common_db.cljc
- src/cljc/athens/common_events/bfs.cljc
- src/cljc/athens/common_events/graph/atomic.cljc
- src/cljc/athens/common_events/graph/ops.cljc
- src/cljc/athens/common_events/graph/schema.cljc
- src/cljc/athens/common_events/resolver/atomic.cljc
- src/cljs/athens/components.cljs
- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/views/pages/block_page.cljs
- src/cljs/athens/views/pages/node_page.cljs
- test/athens/bfs_test.cljc
- test/athens/common_events/atomic_ops/block_save_test.cljc
- test/athens/common_events/atomic_ops/block_split_test.cljc
> rfct: remove old-string from :block/save event

- src/clj/athens/self_hosted/web/datascript.clj
- src/cljc/athens/common_db.cljc
- src/cljc/athens/common_events/resolver/atomic.cljc
- test/athens/common_events/atomic_ops/page_merge_test.cljc
- test/athens/common_events/atomic_ops/page_rename_test.cljc
> fix: `:page/merge` throwing exceptions in `orderkeeper` no more.

- src/cljs/athens/effects.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/self_hosted/client.cljs
- src/cljs/athens/self_hosted/presence/views.cljs
- src/cljs/athens/util.cljs
- rfct: reduce log noise on non-verbose settings
- fix: editing/target should delegate to editing/uid
- fix: embeds show presence as well as the original block
> embed presence

- README.md
- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/subs.cljs
- src/cljs/athens/util.cljs
- src/cljs/athens/views.cljs
- src/cljs/athens/views/app_toolbar.cljs
- src/cljs/athens/views/help.cljs
- src/js/components/AppToolbar/AppToolbar.tsx
- wip: help-popup
- feat(help-popup): Add help popup with content.
- feat(help-popup): Add tooltip to help icon
- feat(help-popup): Fix issue with scroll-bar and move scroll to content of the help.
- feat(help-popup): Remove "code block" from Help.
- feat(help-popup): Comment out help links until we have the correct ones.
- feat(help-popup): Fix border mismatches
- feat(help-popup): Fix spacing
- feat(help-popup): Fix scroll behaviour
- feat(help-popup): Fix a few shortcuts
- feat(help-popup): Fix closing of modal using escape.
- feat(help-popup): Fix copy and remove  a shortcut that doesn't work
- doc: Fix links to Athens Research Blog (#1666)
- rfct: use button tooltip instead
- style: style, lint, carve
> merge main help

- athens.dockerfile
It didn't have `curl` anymore,
and we need it for health-check.
> fix: this docker images was to skinny

- src/cljs/athens/listeners.cljs
Brings up a popup window warning user that edits may not have been saved if user is currently editing a block. 
Discussed in the data loss channel on discord. 
this will close #1898
> fix(data-loss): Quitting athens while editing a block displays no warning and causes data loss. 

- .github/workflows/build.yml
- deps.edn
- dev/notebooks/notebooks.clj
- package.json
- script/vercel-setup.sh
- vercel.json
The secrets necessary for `amondnet/vercel-action` will not be sent for
fork PR builds, so it's not really suitable for usage in our development model.
> build: install dependencies and build on vercel

- src/cljs/athens/listeners.cljs
Pressing escape is the same as clicking cancel, which causes you to
exit.
This way cancel goes back to the db without exiting, which is more natural.
> fix: reverse the buttons on the closing warning

- src/cljc/athens/common_db.cljc
- src/cljc/athens/common_events/bfs.cljc
- src/cljc/athens/common_events/resolver/undo.cljc
- test/athens/bfs_test.cljc
- test/athens/common_db_test.cljc
- test/athens/common_events/atomic_ops/block_open_test.cljc
- test/athens/common_events/atomic_ops/block_remove_test.clj
- feat: build-paste-op returns a flat list of atomic ops
- feat: group block save at the end of paste-op
- fix: don't return repr with uid for title or open true
- feat: support :block/remove in undo
> undo block remove

- src/cljc/athens/common_events/resolver/undo.cljc
- test/athens/common_events/atomic_ops/page_new_test.cljc
The branch this PR is being pushed from `shortcut-page-new` is misnamed. No shortcuts here! Just page-new.
> undo page/new

- src/cljs/athens/self_hosted/presence/views.cljs
https://www.loom.com/share/7c8c1dc2320e44b38fa14b016789a969
No overlap when 1 or 2 avatars. Some overlap when 3 or 4+. (i.e. not @shanberg level design, feel free fix later)
The main problem is the 1 avatar case, i.e. when your own avatar is covering the block you are writing in. If you have 3 or 4 people knowingly in the same block at the same time, you have bigger problems to worry about.
> enhance(presence): move inline avatars to the right

- doc/adr/0021-undo-redo.md
- src/cljc/athens/common_db.cljc
- src/cljc/athens/common_events/resolver/undo.cljc
- test/athens/common_events/atomic_ops/composite_of_composites_undo_test.cljc
- test/athens/common_events/atomic_ops/composite_of_move_undo_test.cljc
- test/athens/common_events/atomic_ops/page_merge_test.cljc
- test/athens/common_events/atomic_ops/page_remove_test.cljc
- test/athens/common_events/fixture.cljc
- docs: add more undo mvp findings
- feat: add :page/merge undo
- fix: don't fail :block/move if ref-block-order is nil
> undo page merge

- src/cljs/athens/views/help.cljs
Changes the instruction in the help popup to show "Toggle Search" instead of "Toggle Athena". 
Believe this to make sense as Athena is not a term that the general end user will likely be familiar with. They will, however, instantly understand if we use the term "Search"
> enhance(help-popup): Use more general term for search shortcut 

- src/cljs/athens/db.cljs
https://www.loom.com/share/e231434d9eb44bd8aeb59bc58f1443c6
I think there's another case where something similar happens: backspace and merge when previous block is more indented.
Is this something that needs tests?
> fix: pressing up and the previous block has a closed child

- package.json
- yarn.lock
This was only needed due to devcards, and we've since removed devcards.
> build: remove marked dependency

- src/cljc/athens/common_events/bfs.cljc
- src/cljs/athens/events.cljs
- src/cljs/athens/views/blocks/content.cljs
- src/cljs/athens/views/blocks/textarea_keydown.cljs
- test/athens/copy_paste_test.cljs
Demos
1a. https://www.loom.com/share/811939853f6646058b481860f0e1d429
1b. https://www.loom.com/share/cd507d3e31a240fa95d5ae65551a03d8
---
1. fixes subtle issues with paste
a. pasting while there is an unsaved local string overwrote it; now it doesn't
b. pasting when on a block that is open with children previously added blocks to the top of the page; now it adds them to the top of the children
2. wasn't able to get tests to runs in Cursive in my REPL, so temporarily using the `fixture/integration-test-fixture`. will remove once the general logic for this PR or I can get the tests to compile in my REPL
3. there is a more general problem regarding 1a. oftentimes user will trigger some sort of graph op while they have an unsaved local-string edit, e.g. paste, indent, enter. Seems like there …
> fix: small paste bugs

- src/cljs/athens/views/blocks/core.cljs
- fix: clicking on a breadcrumb should it as the new parent view
- fix: open/close inline refs should reset breadcrumbs state
> inline refs bugs

- src/cljs/athens/main/core.cljs
Normal mac behavior on clicking the red x is to hide the window so it can be opened instantly from the dock and not have to got through the whole initial boot cycle.
You might want to now move the (prevent-save) function onto this close listener so that on macos it can keep syncing in the background since the window is now hidden but not destroyed.
I'd move (prevent-save) to the window "close" event myself but I have no experience using clojure.
> feat: speedy window re-open on macOS

- src/cljs/athens/effects.cljs
- src/cljs/athens/electron/boot.cljs
- src/cljs/athens/electron/fs.cljs
- src/cljs/athens/events.cljs
Added `:stage/success-db-load` and `:stage/fail-db-load`,
those are used in boot flow.
> fix: boot sequence and db-dump async flows

- src/cljs/athens/effects.cljs
- src/cljs/athens/reactive.cljs
Prevents them from throwing and crashing the app on unexpected boot flows.
> fix: initialize reactive watchers on startup

- src/cljs/athens/listeners.cljs
This change was first introduced in
https://github.com/athensresearch/athens/pull/1899.
It made a lot of sense at the time because it was so easy to lose
content that was being edited.
But now we auto-save after 2s of inactivity in a block, so I don't think
it's as big of a problem anymore.
I do get the warning popup very often so I think now it's doing more
harm than good.
> feat: don't warn on exit while editing

- src/cljc/athens/common/sentry.cljc
- src/cljc/athens/common_db.cljc
- src/cljs/athens/effects.cljs
- src/cljs/athens/electron/boot.cljs
- src/cljs/athens/electron/fs.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/events/remote.cljs
- src/cljs/athens/interceptors.cljs
- src/cljs/athens/router.cljs
- src/cljs/athens/views/hoc/perf_mon.cljs
- src/cljs/athens/views/pages/core.cljs
- src/cljs/athens/views/pages/node_page.cljs
Please review new functions to see if this is what we need out of them:
- `wrap-span-no-new-tx`
- `sentry-span-no-new-tx`
- `hoc-perfmon-no-new-tx`
> Sentry txs limit fix

- src/cljc/athens/parser/impl.cljc
- test/athens/parser/compatibility_test.cljc
Used to be severely broken if block would have a block level
element with 1st line empty like following blockquote
```
>
> Text
```
> fix: Allow to start with empty line

- dev/clj/config.edn
- docker-compose.yml
- src/clj/config.default.edn
Otherwise, adding things like a password via env var means the user has
to also include all docker specific config items.
This commit partially reverts
https://github.com/athensresearch/athens/commit/712759dabe37e4f5a6a61ebc1733e594021c65db.
Paths in the commit above were changed afterwards by https://github.com/athensresearch/athens/commit/f62f829f2cf9347446571ab3c9594443237d2ed3.
> fix: default config should use docker values

- src/cljs/athens/views/left_sidebar.cljs
- src/js/components/AppToolbar/AppToolbar.tsx
- src/js/theme/theme.js
- Various fixes for minor theme issues like improper button background colors in light mode
- Better use of native Chakra button variants like 'ghost'
> improvement: light theme improvements

- src/cljs/athens/electron/db_menu/core.cljs
- src/cljs/athens/electron/db_menu/db_icon.cljs
- src/cljs/athens/electron/db_menu/db_list_item.cljs
- src/cljs/athens/electron/db_menu/status_indicator.cljs
- src/cljs/athens/electron/dialogs.cljs
- src/js/components/Confirmation/Confirmation.tsx
- src/js/components/Icons/Icons.tsx
- Disables the database buttons while Athens is still syncing
- Hides the "synced" status indicator from the DB icon in the toolbar. Spinner means it's working, nothing means it’s done. The 'synced' status indicator was more useful when syncing took longer and was perhaps more fragile.
- Minor style and language enhancements
- This PR blocks in a new 'Confirmation' component to replace the JS confirmation dialog, but is currently unused.
> improvement: ux polish to db menu

- src/cljs/athens/electron/db_modal.cljs
- Show the remote db view in db modal when not electron
> fix: allow remote dbs in web athens

- src/cljs/athens/parse_renderer.cljs
- src/js/components/Block/components/Content.tsx
> Chakra fixes 2

- src/cljs/athens/components.cljs
- src/cljs/athens/views/blocks/context_menu.cljs
- src/cljs/athens/views/blocks/core.cljs
- src/cljs/athens/views/blocks/textarea_keydown.cljs
- src/js/components/Block/components/Anchor.tsx
- Fixes block embed edit button placement
- Restores block cursor up/down functionality
- Moves the definition of block anchor controls into blocks core, out of the Anchor component
- Fixes copy ref/refs behavior and improves the button and toast messaging
> Fix issues 4

- src/js/components/Block/Content.tsx
- src/js/theme/theme.js
- all `mark` elements use the highlight style, not just ones in block content
> fix: mark/highlight colors are global

- resources/public/index.html
- src/cljs/athens/util.cljs
Close https://github.com/athensresearch/athens/issues/1718
Close https://github.com/athensresearch/athens/issues/1705
I tried this PR on firefox and it seems to open ok, so I guess the `case` problem in those issues went away.
> feat: don't autoblock non-chrome browsers

- package.json
- src/cljs/athens/views/pages/all_pages.cljs
- src/cljs/athens/views/pages/node_page.cljs
- src/js/components/AllPagesTable/AllPagesTable.tsx
- src/js/theme/theme.js
- yarn.lock
- All Pages table is virtualized. Only the number of items that fit on the screen are rendered.
- All pages are still pulled from the db, which appears to be the speed limiter now, rather than rendering
- Layout slightly tweaked to support the new architecture
- Uses react-window instead of other libraries because of light weight and ease of use. Other virtualization libraries could be considered.
> Virtualize all pages

- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/listeners.cljs
- src/cljs/athens/router.cljs
- src/cljs/athens/views/blocks/textarea_keydown.cljs
- src/cljs/athens/views/help.cljs
- fix: fold shortcut should use shortcut key on mac
- feat: add navigation section to help
- fix: disable "open file..." dialog on cmd/ctrl+o
- feat: mod+alt+o zooms out of current block
- fix: up on first window child should not lose block focus
- fix: prev-block-uid should not try to go to pages
- fix: :daily-notes/items should always be a vector
- feat: pressing up/down with no focus takes you to last/first block
> Ensure block navigation just through keyboard works

- src/cljs/athens/views/pages/node_page.cljs
Block page refs alread start closed by default so they didn't need to
change.
Please note that 10 is the number of different pages that contain the ref.
> fix: page linked refs start closed when 10+

- src/cljs/athens/events.cljs
There's still a bunch of places that are calling it.
> fix: restore the alert/js event

- src/js/components/References/References.tsx
Linked refs should not be open by default if there are more than 10. However, this was not always working when: linked refs were open for a page, and then user navigates to another page with more than 10 linked refs. `isShowingContent` uses `isOpen` which persists previous linked refs state.
> fix: defaultIsOpen state for linked refs

- src/cljc/athens/common_db.cljc
- src/cljc/athens/common_events/resolver/order.cljc
- src/cljc/athens/common_events/resolver/position.cljc
- src/cljs/athens/db.cljs
- src/cljs/athens/events.cljs
- src/cljs/athens/reactive.cljs
- src/cljs/athens/views/blocks/autocomplete_search.cljs
- src/cljs/athens/views/blocks/core.cljs
- src/cljs/athens/views/blocks/editor.cljs
- src/cljs/athens/views/blocks/internal_representation.cljs
- src/cljs/athens/views/blocks/textarea_keydown.cljs
- src/cljs/athens/views/pages/block_page.cljs
- src/cljs/athens/views/pages/node_page.cljs
- src/js/components/Block/Container.tsx
- src/js/components/Block/PropertyName.tsx
- test/athens/bfs_test.cljc
- test/athens/common_events/resolver/order_test.cljc
- feat: render properties in outliner
- feat: create properties via ::
- fix: removing a child should remove the order number
- feat: backspace at the start of a property will move it to first child
- fix: use db/get-block and get-parent should use common-db helpers
- feat: handle enter on props
- rfct: remove duplicated prev-block-uid code
- rfct: move property sorting into own fn
- feat: add order/get
- feat: handle up/down for properties
- feat: support indent/unindent in properties
- fix: :after/:before prop is not a valid location
- feat: show linked props on page
- feat: show properties in breadcrumbs
- rfct: remove unused rules
- fix: block move should save before moving
- fix: don't create empty prop
- fix: don't show placeholder block when there's props
- feat: allow creation of …
> properties outliner

- src/js/components/Block/Anchor.tsx
- src/js/components/Block/PropertyName.tsx
- src/js/components/Icons/Icons.tsx
Refactors block anchor icons to use icons instead of custom SVGs
> rfct: use standard icons for block element anchors

- src/js/components/Block/Reactions.tsx
- src/js/components/utils/formatList.ts
- Reaction tooltip now linked to whole reaction button
- Tooltip should neatly concatenate list of users who reacted, ("stuart, jeff, and sid reacted with 👍 "
> enhancement: better position, clearer text for reaction tooltip

- src/cljs/athens/views/blocks/editor.cljs
- src/cljs/athens/views/blocks/textarea_keydown.cljs
- src/cljs/athens/views/pages/block_page.cljs
- src/cljs/athens/views/pages/node_page.cljs
- src/cljs/athens/views/pages/settings.cljs
The point of this is to hide property blocks on the outliner, which add a ton of visual noise. The point isn't to turn off all properties code.
> feat: add feature flag for property UIs

- src/cljs/athens/db.cljs
- src/cljs/athens/self_hosted/presence/subs.cljs
- src/cljs/athens/views/app_toolbar.cljs
- src/cljs/athens/views/blocks/context_menu.cljs
- src/cljs/athens/views/blocks/editor.cljs
- src/cljs/athens/views/comments/core.cljs
- src/cljs/athens/views/comments/inline.cljs
- src/cljs/athens/views/pages/block_page.cljs
- src/js/components/AppToolbar/AppToolbar.tsx
- src/js/components/Comments/Comments.tsx
- src/js/theme/theme.js
https://www.loom.com/share/669116c0d0d9476ebe3662f41ef5e8c6
Interesting thing about undo comment deletion is that it rewrites `create/time`
> feat: enable edit and delete of comments

- src/cljs/athens/views/blocks/content.cljs
- src/cljs/athens/views/blocks/editor.cljs
- src/cljs/athens/views/blocks/types/default.cljs
- src/js/components/Block/Container.tsx
- src/js/theme/theme.js
Reverts athensresearch/athens#2266
> Revert "Improve block performance"

- src/js/components/Layout/List.tsx
- src/js/components/Layout/RightSidebar.tsx
- previously dragging and dropping bullets within right sidebar items reordered top-level items, not bullet
- previously space turned on reorder via keyboard
- reference: https://github.com/clauderic/dnd-kit/issues/90
> fix: right sidebar dom events

- src/cljs/athens/views/blocks/core.cljs
- src/cljs/athens/views/comments/core.cljs
- src/cljs/athens/views/notifications/popover.cljs
- don't get notified if someone comments on a block you authored
- see no. of messages on inbox icom
- show comments box when block is closed
> Fix bugs in comments

- package.json
- src/cljs/athens/electron/db_menu/core.cljs
- src/cljs/athens/electron/db_menu/db_list_item.cljs
- yarn.lock
- Fixes focus-fighting warning in db popover
- Removes buttons to remove in-memory db for now
> Fix db dialog issues

- src/cljs/athens/views/athena.cljs
- src/cljs/athens/views/notifications/popover.cljs
- src/js/components/Page/Page.tsx
- src/js/theme/theme.js
Addresses specific cases of "highlight" color to avoid system colors bleeding into the theme.
Punting on theme value naming considerations because that's hard.
> Fix-highlight-colors

- src/cljs/athens/views/pages/node_page.cljs
- src/js/components/Page/Page.tsx
Adds "[icon] Daily Notes" to daily note page headers, as well as some support infrastructure
> feat: add overline to distinguish daily notes

- src/js/components/Page/Page.tsx
Makes sure Daily Notes pages don't think they're allowed to shrink.
Stand proud, Daily Notes. You're worth it.
> fix: daily notes pages shouldn't get squished

- .carve/ignore
- src/cljs/athens/types/tasks/view.cljs
- src/js/components/App/ContextMenuContext.tsx
- src/js/components/Block/Taskbox.tsx
- src/js/components/Icons/Icons.tsx
> leaner task renderer

- src/cljs/athens/views.cljs
- src/cljs/athens/views/right_sidebar/core.cljs
- src/js/components/AppToolbar/AppToolbar.tsx
- src/js/components/Layout/MainContent.tsx
- src/js/components/Layout/RightSidebar.tsx
- src/js/components/Layout/RightSidebarResizeControl.tsx
- src/js/components/Layout/useLayoutState.tsx
- Right sidebar resizes with frontend state, saves to graph after a second
- Layout animation is disabled while resizing
> perf: wait to update sidebar size on graph

- src/cljs/athens/types/tasks/view.cljs
Those are tasks that where converted from old blocks that didn't have
creation time.
> fix: Handle tasks without creation time

- src/js/components/App/ContextMenuContext.tsx
- src/js/components/Block/Anchor.tsx
- src/js/components/Block/Container.tsx
- src/js/components/Comments/Comments.tsx
- src/js/components/Query/KanbanBoard.tsx
Adds optional 'key' prop to `addToContextMenu`, to usable to prevent situations like several blocks providing indistinguishable menus.
> feat: contextmenu offerors are keyed

- src/cljs/athens/self_hosted/presence/views.cljs
- src/cljs/athens/types/tasks/view.cljs
- src/cljs/athens/views/blocks/core.cljs
- src/cljs/athens/views/left_sidebar/tasks.cljs
- src/js/components/AppToolbar/components/LocationIndicator.tsx
- src/js/components/Block/Container.tsx
- src/js/components/Block/Toggle.tsx
- src/js/components/Page/Page.tsx
- src/js/components/PresenceDetails/PresenceDetails.tsx
- src/js/theme/theme.js
Main goal is to improve tasks by adding to the task editor form, not showing less-useful info, and by decluttering the space around them.
Major
- Adds read-only title, creator, and created date to task editor forms
- Hides creator and created date from task blocks
- Adds pencil icon to task blocks to slightly afford editing
Minor
- Block toggles hidden (once again) until hovering/editing that block
- Fixes missing focus outlines due to new defaults from Chakra
- Moves block presence and ref count into right page gutter
> More on tasks

- src/js/components/Layout/RightSidebar.tsx
Moves the scrolling containment to the inner box in the right sidebar, so the drag handle isn't part of the scrolling area.
> fix: right sidebar drag handle doesn't scroll away

- src/js/theme/theme.js
Minor fix to hide focus rings again unless using the keyboard.
This had been updated when we were upgrading to chakra 2, but wasn't reverted when we pulled back.
> fix: restore focus behavior prior to chakra update

- src/js/components/Layout/RightSidebar.tsx
Right sidebar contents should align with top of daily notes and left sidebar elements
> fix: right sidebar els align to top

- src/cljs/athens/parse_renderer.cljs
- src/cljs/athens/types/core.cljs
- src/cljs/athens/types/default/view.cljs
- src/cljs/athens/types/tasks/view.cljs
- src/cljs/athens/views/right_sidebar/shared.cljs
- test/athens/types_test.cljs
> feat: Parsing to text wraps block-refs in `(())`

- src/js/components/Layout/RightSidebar.tsx
Not sure why, but it seems like chakra `layerStyles` aren't working. Not sure that's worth debugging, so I've refactored to just use normal styles.
> fix: right sidebar items have proper bg

- src/cljs/athens/views.cljs
- src/cljs/athens/views/notifications/popover.cljs
- src/cljs/athens/views/pages/daily_notes.cljs
- src/js/components/AllPagesTable/AllPagesTable.tsx
- src/js/components/Block/Autocomplete.tsx
- src/js/components/Layout/MainSidebar.tsx
- src/js/components/Layout/RightSidebar.tsx
- src/js/components/Page/Page.tsx
- src/js/theme/theme.js
Slightly better tablet support by using dynamic viewport height units, where supported.
Fixes some elements not appearing on e.g. the bottom of an iPad.
> Fix page height on mobile

- src/cljs/athens/views/blocks/core.cljs
- src/cljs/athens/views/blocks/editor.cljs
- src/cljs/athens/views/pages/node_page.cljs
After the recent code changes the `.block-page` and `.node-page` class names were removed => the following line in `athens.views.blocks.editor/find-selected-items` returns `nil` which makes it impossible to do manipulations with multi-line texts.
```clj
(or (.. target (closest ".node-page"))
(.. target (closest ".block-page")))
```
This PR fixes that.
> .block-page and .node-page class names added

- package.json
- src/cljs/athens/utils/markdown.cljs
- src/cljs/athens/views/blocks/editor.cljs
- yarn.lock
Makes it possible to paste complex data such as lists and formatted HTML text to Athens. 
The original goal of it was to make it possible to insert nested lists from different sources while maintaining the structure.  I wanted to extend the parser and make it work with HTML first but quickly figured that the easiest would be to just get the HTML data (`text/html`) from the clipboard and transform it to markdown — this solution makes it possible to not only work with lists but with literally any rich data.
**How to test:**
1. Go to any source of rich data (I was using https://github.com/HumbleUI/HumbleUI#motivation)
2. Just copy the HTML and paste it to Athens.
3. You can also insert the raw data in Markdown format, it will also be parsed and inserted correctly.
> Get clipboard data in HTML format
