CONTRIBUTING.md

Will focus on making specific dev environment setup instructions for ios, windows, and linux next PR.
Imo sections about governance, etc. can wait til we have more contributors. I kind of want to talk to you about those issues before I start writing them as well.

doc: edit CONTRIBUTING to include style guide info

---

CONTRIBUTING.md

Once these changes are approved, we will need to change README to remove the "Getting Started" section. We may want to do a full revamp of the README page.

docs: added detailed dev env setup

---

.github/workflows/build.yml
project.clj
script/test/all
script/test/jvm
src/cljc/athens/blocks.cljc
src/cljs/athens/subs.cljs
test/athens/block_test.clj

Resolves #15 and #27 
Github Action result: https://github.com/jeroenvandijk/athens/runs/650337222
Run locally
```
script/test/jvm
```
or later when we have cljs tests
```
script/test/all
```

Unit test (setup) and CI

---

src/cljs/athens/core.cljs
src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/subs.cljs
src/cljs/athens/views.cljs

closes #11 
Uses `day8.re-frame.async-flow-fx`

fix: closes #11

---

src/cljs/athens/subs.cljs
src/cljs/athens/views.cljs

- close #19
- move "Current Route /foo" and "All Pages" link to sidebar

feature: create left sidebar

---

README.md

Athens is rad. Took me a tad too long to understand the instructions so I did some rewording. Hope you like it!

docs: some rewording of the getting started instructions

---

src/cljs/athens/events.cljs
src/cljs/athens/page.cljs
src/cljs/athens/subs.cljs

closes #7
Still need to re-ordering, but can make another issue for that. A little more complex.

feature: toggle open/close state of block

---

.github/workflows/build.yml
script/build/athens-app
shadow-cljs.edn
src/cljs/athens/core.cljs

fix: boot error in prod mode

---

.clj-kondo/config.edn
src/cljs/athens/core.cljs
src/cljs/athens/db.cljs
src/cljs/athens/devcards.cljs
src/cljs/athens/events.cljs
src/cljs/athens/page.cljs
src/cljs/athens/parser.cljs
src/cljs/athens/router.cljs
src/cljs/athens/subs.cljs
src/cljs/athens/views.cljs
src/cljsjs/create_react_class.cljs

Fix: clj-kondo linter warnings

---

README.md

Easing the user experience in finding other social media related to the project. It was difficult for me to find the discord for example.

Added Social media buttons

---

CONTRIBUTING.md
README.md

- simplify the cluttered install directions
- remove personal pronouns ("I")
- point to other resources, but pull in the parts that were important
- to me

docs: update CONTRIBUTING and README to use Notion docs

---

CONTRIBUTING.md

Had to find information for getting th project up and running on the discord felt it should be in the contribution doc

docs: Add commands for bringing up dev enviroment

---

.github/workflows/build.yml
deps.edn
script/carve
script/style

fails if fixes are found ([last run](https://github.com/jeroenvandijk/athens/runs/674359114#step:3:21))
fails if superfluous vars are found ([last run](https://github.com/jeroenvandijk/athens/runs/674359202#step:4:118))
Fix the checks and/or tweaking the configuration. Probably good for beginners. Link to docs is in `script/style` and `script/carve`

Add code style + unused vars checks

---

src/cljs/athens/style.cljs
src/cljs/athens/views.cljs

@tangjeff0, @Smittyvb and others what do you think about this way of composing styles in a separate style file.
@Smittyvb already made a start with some first functions. Here I've extracted some boilerblate and showed how you can compose styles and classes together.
* (Logic) of styles are in one place
* Unused styles are removed because of `script/carve` that looks for unused vars
* Refactoring of styles (inline to classes, different frameworks etc) doesn't affect the other view code as that part can keep using the function and doesn't care about it's implementation.
(More background here https://github.com/athensresearch/athens/issues/10)

CSS composition

---

src/cljs/athens/views.cljs

Properly formatted the hiccup in the about-panel, table, and pages-panel functions

views.cljs code style refactor

---

CONTRIBUTING.md
script/carve
script/style

Devcards instructions were based on https://github.com/athensresearch/athens/pull/109#issuecomment-636395081

Document in CONTRIBUTING.md how to run tests and devcards

---

src/cljc/athens/lib/dom/attributes.cljc
test/athens/lib/dom/attributes_test.cljc

feat(style-guide): composable css styles

---

src/cljs/athens/devcards/db.cljs
src/cljs/athens/devcards/table.cljs

closes #118 
https://tangjeff0.github.io/athens/cards.html#!/athens.devcards.table

feat(devcards): give user buttons to load real or mock data

---

.carve_ignore
resources/public/index.html
src/cljc/athens/lib/dom/attributes.cljc
src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/all_pages.cljs
src/cljs/athens/devcards/left_sidebar.cljs
src/cljs/athens/router.cljs
src/cljs/athens/style.cljs
src/cljs/athens/views.cljs
test/athens/lib/dom/attributes_test.cljc

Imports #99 #100 #103 into actual app.
Will add remaining bugs/tasks/refactors for other contributors to tackle to these issues!

Import devcards to project

---

package.json
yarn.lock

- Adds missing dependencies to project, despite project apparently working fine without.

fix(icons): add missing dependencies

---

src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/db_boxes.cljs

Initial try at providing #67. Since it is in a working state I thought this might be a good time for a PR.
Without a doubt things could be better, so I'm open to all feedback and suggestions.

Datascript explorer

---

src/cljs/athens/devcards/all_pages.cljs
src/cljs/athens/devcards/left_sidebar.cljs
src/cljs/athens/page.cljs
src/cljs/athens/style.cljs
src/cljs/athens/views.cljs

- Use flexbox for overall app layout

refactor(layout): flexbox for app layout

---

src/cljs/athens/devcards/athena.cljs
src/cljs/athens/devcards/icons.cljs
src/cljs/athens/devcards/left_sidebar.cljs
src/cljs/athens/style.cljs

refactor(style): polish icons and buttons

---

src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/styling_with_stylefy.cljs

Add DevCard documenting styling with Stylefy. [Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.styling_with_stylefy)

feat(docs): document styling with stylefy

---

src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/devcards/parser.cljs
src/cljs/athens/parse_renderer.cljs

Follows through on https://github.com/athensresearch/athens/issues/94#issuecomment-640863780

feat(parser): setup basic devcards

---

src/cljs/athens/db.cljs
src/cljs/athens/devcards/all_pages.cljs
src/cljs/athens/devcards/athena.cljs
src/cljs/athens/devcards/block_page.cljs
src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/devcards/buttons.cljs
src/cljs/athens/devcards/db.cljs
src/cljs/athens/devcards/left_sidebar.cljs
src/cljs/athens/devcards/node_page.cljs
src/cljs/athens/devcards/style_guide.cljs

Please document/refactor Devcards in the style of `all_pages.cljs` in this PR.
- link to GH feature issue(s), if available
- ~~define globals at top. usually just dsdb, if needed~~ no longer doing this
- organize code by section, e.g.
```
;;; Styles
;;; Components
;;; Devcards
```
- Use semi-colons per https://guide.clojure.style/#three-semicolons-for-top-level-comments
- get rid of wrapper/helper functions in `db.cljs`
```
(defn new-conn
[]
(d/create-conn db/schema))
(defn posh-conn!
[conn]
(posh! conn))
```
- wherever they are used, replace them with original datascript and posh functions
```
(defonce conn (d/create-conn db/schema))
(posh! conn)
```

refactor(devcards): documenting and refactoring devcards

---

resources/public/cards.html
resources/public/css/normalize.css
resources/public/index.html

Adds normalize.css to keep from having to deal with browser quirks and inconsistencies, particularly during development.

feat(style): add normalize css

---

src/cljs/athens/devcards/athena.cljs
src/cljs/athens/devcards/left_sidebar.cljs
src/cljs/athens/listeners.cljs
src/cljs/athens/views.cljs

- exit with ESC or click outside

refactor(athena): separate into elem and component. proper exit

---

src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/spinner.cljs
src/cljs/athens/views.cljs

[Devcard](https://shanberg.github.io/athens/cards.html#!/athens.devcards.spinner)
Add loading spinner component

Add loading spinner

---

resources/public/index.html
shadow-cljs.edn
src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/all_pages.cljs
src/cljs/athens/devcards/athena.cljs
src/cljs/athens/devcards/block_page.cljs
src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/devcards/left_sidebar.cljs
src/cljs/athens/devcards/spinner.cljs
src/cljs/athens/parse_renderer.cljs
src/cljs/athens/router.cljs
src/cljs/athens/views.cljs

accidentally merged two PRs at once

refactor `navigate-page` and call spinner from JS

---

src/cljs/athens/devcards/block_page.cljs
src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/devcards/node_page.cljs
src/cljs/athens/listeners.cljs

- add listeners for titles
- remove instances of `dbid`. can just use [:block/uid uid]
- do block destructuring as a parameter rather than in `let` block

feat(page): editable titles

---

src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/parse_renderer.cljs
src/cljs/athens/style.cljs

Minor polish to links and such in blocks.

feat(blocks): cleaner parsed text

---

src/cljs/athens/events.cljs
src/cljs/athens/listeners.cljs

Really proud about this datalog

Implement much more indent/unindent and Drag n' Drop using proper Datalog

---

src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/events.cljs

Taking a break from writing features to set up scaffolding for other not-yet-started features that others (designers) can work on in parallel

Textarea keydown. WIP

---

src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/filters.cljs

feat(filters): mock data

---

src/cljs/athens/devcards/filters.cljs

[Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.filters)
Style new filters control

Polish filters

---

src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/textinput.cljs

[Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.textinput)
Adds basic input component.

Add input component

---

src/cljs/athens/devcards/textinput.cljs

Very minor: use the proper data structure to apply input border style with available style variables

refactor(Input): inputs properly declare their border color

---

src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/devcards/node_page.cljs

Page titles use editing style similar to blocks.

Style title editing

---

src/cljs/athens/devcards/blocks.cljs

Improved styles and UX for tooltips when hovering block bullets

feat(Blocks): improved block tooltip UX

---

shadow-cljs.edn
src/cljs/athens/devcards/buttons.cljs
src/cljs/athens/devcards/devtool.cljs
src/cljs/athens/devcards/left_sidebar.cljs
src/cljs/athens/devcards/right_sidebar.cljs
src/cljs/athens/devcards/textinput.cljs
src/cljs/athens/style.cljs
src/cljs/athens/views.cljs

Style devtool

---

src/cljs/athens/devcards/devtool.cljs

fix(Devtool): no more redundant trueness

---

src/cljs/athens/db.cljs
src/cljs/athens/devcards/block_page.cljs
src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/devcards/node_page.cljs
src/cljs/athens/devcards/right_sidebar.cljs
src/cljs/athens/events.cljs
src/cljs/athens/listeners.cljs
src/cljs/athens/parse_renderer.cljs
src/cljs/athens/router.cljs
src/cljs/athens/style.cljs
src/cljs/athens/subs.cljs

Restyled sidebar.
Some controls are commented out, waiting on additional functionality: item reordering, filtering...

Polish sidebar 2

---

.clj-kondo/config.edn
src/cljc/athens/parser.cljc
src/cljc/athens/util.cljc
src/cljs/athens/devcards/athena.cljs
src/cljs/athens/devcards/node_page.cljs
src/cljs/athens/events.cljs

Lots of TODOs and FIXMEs in the code - left for future contributors :)

Athena new page

---

src/cljc/athens/lib/dom/attributes.cljc
src/cljs/athens/db.cljs
src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/devcards/node_page.cljs

- fixes an issue created in #203 where block writing failed

Linked references

---

src/cljs/athens/devcards.cljs
src/cljs/athens/devcards/buttons.cljs
src/cljs/athens/devcards/dropdown.cljs
src/cljs/athens/devcards/filters.cljs

[Demo](https://shanberg.github.io/athens/cards.html#!/athens.devcards.dropdown). Adds new Dropdown component.

Dropdown devcard

---

src/cljs/athens/devcards/all_pages.cljs
src/cljs/athens/devcards/block_page.cljs
src/cljs/athens/devcards/node_page.cljs
src/cljs/athens/views.cljs

[Demo](https://shanberg.github.io/athens/#/pages)
- Node and block pages should sit in the middle of the layout
- All Pages table should be centered and have some spacing/padding

fix(layout): fix numerous minor layout issues

---

src/cljs/athens/devcards/blocks.cljs

feat(blocks): open parent blocks show indicator line

---

src/cljs/athens/db.cljs
src/cljs/athens/devcards/all_pages.cljs
src/cljs/athens/devcards/blocks.cljs
src/cljs/athens/devcards/node_page.cljs
src/cljs/athens/events.cljs

TODO: backspace in a nested block joins parent and block text together

feat(block): backspace (WIP), enter, focus on editing textarea. decouple fns from fx

---

src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/views/blocks.cljs
src/cljs/athens/views/node_page.cljs

feat(blocks): arrow key navigation, more *effectful* backspace/enter functionality

---

src/cljs/athens/devcards/devtool.cljs

A few more dependencies I missed

Add missing devtool devcard deps

---

src/cljs/athens/events.cljs
src/cljs/athens/views/blocks.cljs

- complexity stems from many edge cases
- must manage both mouse event handlers and UI
- don't thoroughly understand e.preventDefault e.stopPropagation
- last child problem. by default, have a top-level drag and drop above
the block. what about the last child?
- 3 places: above block, child block, and below block if last block
I'm probably doing this wrong, so leaving this incomplete. Going to
make a start on block selection as it also uses drag events. May find
the answer to my questions there.

feat(blocks): drag and drop progress but incomplete. see comments

---

src/cljs/athens/events.cljs

small fix, cc @nthd3gr33 @itsrainingmani @alaq

fix(block): fix unindent on date pages

---

src/cljs/athens/parse_renderer.cljs
src/cljs/athens/views/node_page.cljs

feat(blocks): nested link support

---

src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/keybindings.cljs
src/cljs/athens/listeners.cljs
src/cljs/athens/subs.cljs
src/cljs/athens/views/blocks.cljs

- backspace deletes all selected
- enter re-focuses top block
- todo: spec behavior for indent
- todo: drag to select multiple blocks
- todo: if shift-up to parent, don't highlight twice. then delete recursively

feat(block): block selection with shift-up/down

---

project.clj
src/cljs/athens/events.cljs

https://github.com/tonsky/datascript/releases/tag/1.0.0

feat(datascript): upgrade 1.0.0, use :keys

---

src/cljs/athens/events.cljs
src/cljs/athens/listeners.cljs
src/cljs/athens/views/blocks.cljs

- pretty much correct drop area indicators
- drop below works 
- partial drag to select multiple blocks

feat(blocks): Drag n drop v3, partial drag select for multiple blocks

---

src/cljc/athens/parser.cljc
src/cljs/athens/parse_renderer.cljs

See also: https://github.com/athensresearch/athens/issues/240#issuecomment-659948413
<s>Couldn't pass the test suite because</s> the unicode bare tags wouldn't be recognized in this config. Really curious if anyone knows how to address this problem. _Edit: used temporary solution to most of the use cases. Still curious to see what's the best practice though!_
Edit: Demo here: <https://haojixu.github.io/athens>
Thanks :)

(experimental) fix(parser): performance fix for parser using LL(1)-like parsing

---

src/cljs/athens/events.cljs
src/cljs/athens/views/blocks.cljs
src/cljs/athens/views/node_page.cljs

refactor(block): use stylefy/class

feat(blocks): shift click for multi block select first pass

---

CONTRIBUTING.md

docs: windows env setup using WSL 2 #248

Windows env setup using WSL 2

---

src/cljs/athens/util.cljs
src/cljs/athens/views/blocks.cljs
src/cljs/athens/views/node_page.cljs

<s>Currently waiting for page deletion from <https://github.com/athensresearch/athens/pull/295>.</s>
Update: integrated #295 and added full page deletion.

feat(blocks): add hashtag page auto-create and auto-delete

---

src/cljs/athens/db.cljs

+ code is more simple
- sligthly more complex computation

rfct: simpler code for count function

---

src/cljs/athens/keybindings.cljs

rfct: dec inc index in cycle

---

src/cljs/athens/views/blocks.cljs

fix(blocks): robustly check for page auto deletion

---

package.json
project.clj
src/cljs/athens/core.cljs
src/cljs/athens/views/spinner.cljs
yarn.lock

https://day8.github.io/re-frame/releases/2020/

chore(deps): update re-frame to 1.0.0

---

src/cljs/athens/util.cljs

- separate logic and effect
- scroll-top! can be registered as re-frame effect handler

refactor "scroll if needed" function

---

src/cljs/athens/views/node_page.cljs

feat(page): navigation by click or shift click

---

src/cljs/athens/listeners.cljs
src/cljs/athens/views/blocks.cljs

- partly addresses #330 
- still need to do cut
- but need to fix block selection first

Copy and paste block uids

---

.github/workflows/build.yml
package.json
shadow-cljs.edn
src/cljs/athens/listeners.cljs
src/cljs/athens/main/core.cljs

Don't always publish. Publish with version bumping via https://github.com/samuelmeuli/action-electron-builder#releasing.

fix(electron): some but not all warnings gone

---

project.clj
src/cljs/athens/events.cljs

https://day8.github.io/re-frame/releases/2020/

chore(reframe): update to 1.1.0 and replace deprecated dispatch-n

---

src/cljs/athens/events.cljs

- Using `:transact` event instead of effect, so sync dot turns yellow each time datoms are written!
- closes https://github.com/athensresearch/athens/projects/4#card-44048070

rfct(effects): use :transact event everywhere w/ new reframe :fx

---

src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/parse_renderer.cljs
src/cljs/athens/views/blocks.cljs
src/cljs/athens/views/left_sidebar.cljs

- show block ref count badge UI
- closes #351

feat(parser): add/remove block refs to datascript when writing

---

src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/listeners.cljs
src/cljs/athens/views/blocks.cljs

- selection bugs fixed! can finally close #330

feat: multi-block deletion reindexes properly

---

src/cljs/athens/views/block_page.cljs

feat(block-page): Add enter handler on zoomed block

---

src/cljs/athens/keybindings.cljs
src/cljs/athens/parse_renderer.cljs
src/cljs/athens/views/blocks.cljs

- also fix `parse-renderer` to show nested elements and `navigate-uid` properly

feat(inline-search): works for hashtags now

---

.github/workflows/build.yml
build/entitlements.mac.plist
package.json
yarn.lock

resources
- https://github.com/samuelmeuli/action-electron-builder#notarization
- https://samuelmeuli.com/blog/2019-12-28-notarizing-your-electron-app/
- https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/
- https://help.attendify.com/en/articles/441408-how-to-export-a-distribution-certificate-as-a-p12-file
- blog.brainio.com
adds env
- API_KEY
- API_KEY_ID
- API_KEY_ISSUER_ID
- MAC_CERTS
- MAC_CERTS_PASSWORD
switch from Amazon S3 to GH Releases

feat(electron): macOS build w/ notary + code signing. GH Releases

---

src/cljs/athens/keybindings.cljs
src/cljs/athens/views/block_page.cljs
src/cljs/athens/views/blocks.cljs
src/cljs/athens/views/node_page.cljs

- closes https://github.com/athensresearch/athens/projects/4#card-46048536

feat(auto-complete): user can now expand auto-completes using click

---

src/cljs/athens/views/app_toolbar.cljs
src/cljs/athens/views/daily_notes.cljs

- fix(toolbar): update icon active state reactively
- fix(toolbar): center sync UI
- fix(daily-notes): simplify logic using `some->>` and sort daily-notes

fix(toolbar): update icon active state reactively; fix(toolbar): center sync UI; fix(daily-notes): simplify logic using some->> and sort daily-notes

---

src/cljs/athens/events.cljs
src/cljs/athens/views/block_page.cljs

Supercedes #365, `clj-kondo` is being weird.

feat(block-page): split header creates new child on enter

---

src/cljs/athens/events.cljs
src/cljs/athens/listeners.cljs

feat(copy): copy nested blocks as an outline, not a flat list
feat(paste): paste plaintext as blocks

feat(copy,paste): support nested now, not just flat

---

src/cljs/athens/events.cljs

https://github.com/athensresearch/athens/projects/4#card-46395202
- also fragments `:enter` into multiple events

fix: indent from enter. append on closed block w children. rfct

---

src/cljs/athens/events.cljs
src/cljs/athens/views/block_page.cljs

- DONE: backspace on zeroth block takes user back to header

fix(block-page): enter adds another block, backspace goes to header

---

resources/public/textarea.js
src/cljs/athens/keybindings.cljs
src/cljs/athens/util.cljs
src/cljs/athens/views/blocks.cljs

https://github.com/component/textarea-caret-position
https://stackoverflow.com/questions/15020669/clojure-multiline-regular-expression

feat(textarea): get caret position

---

src/cljs/athens/db.cljs
src/cljs/athens/electron.cljs
src/cljs/athens/events.cljs
src/cljs/athens/views/app_toolbar.cljs

feat(electron): watch filesystem for db updates. remove sync UI

---

src/cljs/athens/main/core.cljs

Previously, had to restart manually to install update. Now auto restart.
https://www.electron.build/auto-update.html#module_electron-updater.AppUpdater+quitAndInstall

feat(electron): restart automatically when update is found

---

CONTRIBUTING.md

doc: Update Calva docs

---

src/cljs/athens/views/node_page.cljs

fix(UI): change page menu icon

---

resources/public/index.html
src/cljs/athens/effects.cljs
src/cljs/athens/electron.cljs
src/cljs/athens/router.cljs
src/cljs/athens/style.cljs
src/cljs/athens/util.cljs

- if 1st time opening, open left sidebar and open daily notes. before, user went to Welcome page

fix(10x): toggle works better; feat(boot): smarter startup events

---

src/cljs/athens/athens_datoms.cljs

`When your restart Athens...` -> `When you restart Athens...`

typo in welcome page

---

.github/workflows/build.yml
package.json

Actually coulda worked the whole time. Never needed `tools-deps` for the release step.

feat(electron): build windows

---

src/cljs/athens/electron.cljs

Short-term fix #466. Prompts user to open a pre-existing db.
Doesn't give option to *create* a new db, so user must have a pre-existing one :)

feat(electron): prompt user to open db if not found on fs

---

src/cljs/athens/main/core.cljs
src/cljs/athens/views/app_toolbar.cljs

This reverts commit 70805c8b525895486fb21fa671dd65e9ea35fe88 #475 
I shoulda pulled this in locally before merging! cc @shanberg

revert: "feat: hide electron title bar (#475)"

---

src/cljs/athens/views/blocks.cljs

fix(ui): text should be left aligned

---

src/cljs/athens/keybindings.cljs

before/after: https://www.loom.com/share/e185326994854c9aafe5c75969fafa90

fix(keybindings): don't allow / # to reset search/type if not nil

---

src/cljs/athens/electron.cljs
src/cljs/athens/subs.cljs
src/cljs/athens/views/blocks.cljs

Filesystem directory naming stuff should be refactored into utilities.

feat(image): drag and drop or ctrl-v to paste image

---

CONTRIBUTING.md
project.clj

Added cider-nrepl as a development dependency

docs: Added documentation for vim-fireplace

---

src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/subs.cljs
src/cljs/athens/views/right_sidebar.cljs

demo: https://www.loom.com/share/7f4ca483cdc74cf4a9be7c84352ff384
resources: 
- day8/re-frame-10x@master/src/day8/re_frame_10x.cljs
- blog.logrocket.com/building-resizable-react-component-using-custom-react-hooks

feat(right-sidebar): make resizable

---

src/cljs/athens/views/blocks.cljs

Previously, used `n` of clipboard-items to determine if screenshot should be pasted or not. But `n` can be variadic length. `n` is two if copying a picture from web or file explorer. `n` is one if copying screenshot directly to clipboard.
TODO: handle images interleaved with text.

feat(paste): handle paste after copy screenshot to clipboard

---

resources/public/index.html

feat: add open-source product analytics

---

src/cljs/athens/events.cljs
src/cljs/athens/views/blocks.cljs

fix(#512): don't crash when trying to update deleted block

---

src/cljs/athens/db.cljs
src/cljs/athens/effects.cljs

rfct: remove unnecessary relationship retraction functions

---

resources/public/index.html
src/cljs/athens/effects.cljs

North Star of Athens: links created
Bidirectional links as a Tool for Thought.

feat(telemetry): use localStorage, gamify link creation

---

.carve_ignore
src/cljs/athens/db.cljs
src/cljs/athens/effects.cljs
src/cljs/athens/views/node_page.cljs

fix(merge-pages): do not retract block/ref if with-db already retracts

---

src/cljs/athens/effects.cljs

Discovered by @juniusfree https://discord.com/channels/708122962422792194/708122962905006203/801596821868249108

fix: last PR runs REPL code

---

src/cljs/athens/electron.cljs

Based off of [recommendation by @pithyless](https://github.com/athensresearch/athens/discussions/590#discussioncomment-329333), but uses `copyFile` instead of `rename` to persist a backup.

feat(electron): eliminate common race condition, create n backups

---

src/cljs/athens/main/core.cljs

Need someone who can test this out on Mac with me before deploy.
Have you tried building locally yet on @seltzered?

feat(electron): clicking on app icon on mac should init Athens

---

README.md

added user onboarding, feature request, and bug report links to readme

Add loom links to README.md

---

src/cljs/athens/parse_renderer.cljs

Fix #615 
Left: before, right: after.

fix(UI): Change page-link style to fix issue #615

---

.github/workflows/build.yml

fix windows sentry variable https://github.com/athensresearch/athens/pull/623
https://github.com/juniusfree/athens/runs/1868201203?check_suite_focus=true

fix: windows sentry variable

---

src/cljs/athens/parse_renderer.cljs
src/cljs/athens/router.cljs

Accidentally merged in #635 which had an incorrect fix.

fix: #635, only open in right sidebar on SHIFT-click

---

src/cljs/athens/parse_renderer.cljs
src/cljs/athens/views/node_page.cljs

fix: linked reference should show the formatting

---

src/cljc/athens/parser.cljc

fix(parser): parse bare urls #549

---

package.json

chore: standard-version, organize package.json

---

package.json
src/cljs/athens/router.cljs
src/cljs/athens/views.cljs
src/cljs/athens/views/app_toolbar.cljs
src/cljs/athens/views/graph_page.cljs
yarn.lock

Related: https://github.com/athensresearch/athens/discussions/605
Demo: https://www.loom.com/share/2e5d9c9b7a6f48d38c6bd484f64e5f90

feat(graph-viz): first pass

---

package.json
src/cljs/athens/core.cljs
src/cljs/athens/views.cljs
src/cljs/athens/views/app_toolbar.cljs
src/cljs/athens/views/settings_page.cljs
yarn.lock

enhance(analytics): opt-out includes Sentry, don't capture info logs, global alert

---

CONTRIBUTING.md

PR updates `CONTRIBUTING.md` with current discord channel names

doc(Discord): Update discord channel names

---

src/cljs/athens/db.cljs
src/cljs/athens/keybindings.cljs
src/cljs/athens/views/blocks.cljs

fix(keybinding):block save before navigation #612

---

src/cljs/athens/electron.cljs
src/cljs/athens/events.cljs
src/cljs/athens/views/settings_page.cljs

enhance(sync): if remote changes detected, ask user to confirm changes

---

src/cljs/athens/events.cljs
src/cljs/athens/views/block_page.cljs
src/cljs/athens/views/right_sidebar.cljs

https://www.loom.com/share/44c8abd4fb0249c5b327a481816a9690

fix(right-sidebar): click on breadcrumb should stay in right sidebar

---

src/cljs/athens/views/settings_page.cljs

feat(settings): let user auth with OpenCollective email

---

src/cljs/athens/events.cljs
src/cljs/athens/router.cljs
src/cljs/athens/util.cljs
src/cljs/athens/views/daily_notes.cljs
src/cljs/athens/views/node_page.cljs

https://www.loom.com/share/3b1d9b8f49ef43fc95723bf1d0fc7492
close #638 
close #528

fix(daily-notes): guard against invalid pull, no more error message

---

src/cljs/athens/core.cljs
src/cljs/athens/events.cljs
src/cljs/athens/util.cljs
src/cljs/athens/views/settings_page.cljs

enhance(electron): remember window size

---

src/cljs/athens/main/core.cljs

fix(electron): make sure main-window exists before sending

---

resources/public/index.html
shadow-cljs.edn
src/cljs/athens/style.cljs
src/cljs/athens/util.cljs
src/cljs/athens/views.cljs

perf(shadow): use release build

---

package.json

Fix typo in package.json's standard-version.types.style

fix(typo):  package.json hiddren->hidden

---

src/cljs/athens/views/graph_page.cljs

Also respecting `Shift+Click` behaviour.

enhance(graph): clicking on node navigates to page

---

src/cljs/athens/views/app_toolbar.cljs
src/cljs/athens/views/left_sidebar.cljs

feat(toolbar): add a "Load Test DB" button for web demo

---

.clj-kondo/config.edn
.github/workflows/build.yml
src/cljs/athens/components.cljs
src/cljs/athens/views/graph_page.cljs

see https://github.com/clj-kondo/clj-kondo/issues/1201 and #767
cc @arkRedM @borkdude

fix(clj-kondo): upgrade CI, with-let, specter, remove #_:clj-kondo/ignore

---

src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/views/graph_page.cljs

fix(web): theme and graph conf issue #773

---

src/cljs/athens/components.cljs
src/cljs/athens/devcards/buttons.cljs
src/cljs/athens/devcards/icons.cljs
src/cljs/athens/devcards/textinput.cljs
src/cljs/athens/keybindings.cljs
src/cljs/athens/views/alerts.cljs
src/cljs/athens/views/app_toolbar.cljs
src/cljs/athens/views/athena.cljs
src/cljs/athens/views/block_page.cljs
src/cljs/athens/views/blocks.cljs
src/cljs/athens/views/devtool.cljs
src/cljs/athens/views/dropdown.cljs
src/cljs/athens/views/filesystem.cljs
src/cljs/athens/views/filters.cljs
src/cljs/athens/views/graph_page.cljs
src/cljs/athens/views/node_page.cljs
src/cljs/athens/views/right_sidebar.cljs
src/cljs/athens/views/settings_page.cljs

This reverts commit e60d92fb9d1235d205f868d91fbce6935617d254.

revert: "perf(icons): optimize size of material-ui/icons (#790)"

---

src/cljs/athens/components.cljs
src/cljs/athens/devcards/buttons.cljs
src/cljs/athens/devcards/icons.cljs
src/cljs/athens/devcards/textinput.cljs
src/cljs/athens/keybindings.cljs
src/cljs/athens/views/alerts.cljs
src/cljs/athens/views/app_toolbar.cljs
src/cljs/athens/views/athena.cljs
src/cljs/athens/views/block_page.cljs
src/cljs/athens/views/blocks.cljs
src/cljs/athens/views/devtool.cljs
src/cljs/athens/views/dropdown.cljs
src/cljs/athens/views/filesystem.cljs
src/cljs/athens/views/filters.cljs
src/cljs/athens/views/graph_page.cljs
src/cljs/athens/views/node_page.cljs
src/cljs/athens/views/right_sidebar.cljs
src/cljs/athens/views/settings_page.cljs

Bundle size is still reduced but now the electron app will successfully start up.

fix(icons): fix #792

---

package.json

Let's publish all our releases on GitHub. S3 was for when we were doing closed beta.
Ignore changelog and tag number. Have to increment tag, but can delete them when this works.
Keep getting this error:
```
HttpError: 403 Forbidden
{
"message": "Resource not accessible by integration",
"documentation_url": "docs.github.com/rest/reference/repos#create-a-release"
}
```
Documentation for release server: https://www.electron.build/configuration/publish
Any thoughts @sboesen ?

chore: S3 -> GitHub release

---

src/cljs/athens/views/block_page.cljs
src/cljs/athens/views/node_page.cljs

close https://github.com/athensresearch/athens/issues/775

fix(title): shift-click on title should open in right sidebar

---

src/cljs/athens/views/node_page.cljs

fixing an issue introduced in #802

fix: clicking the date doesn't open the date page

---

src/cljs/athens/views.cljs
src/cljs/athens/views/right_sidebar.cljs

Fixed the css property name in #809

fix: toolbar overlaps on scrollbar

---

.gitignore
src/cljs/athens/events.cljs
src/cljs/athens/views/blocks.cljs

feat(block-ref): shift + "Drag'n'Drop" to copy block uid

---

src/cljs/athens/views/left_sidebar.cljs

https://discord.com/channels/708122962422792194/800442937602342922/826962238522785832

fix: url to changelog

---

src/cljs/athens/views/blocks.cljs

feat(copy): right-click to copy without formatting

---

.github/workflows/build.yml

Reran https://github.com/athensresearch/athens/actions/runs/709237766 3 times, always getting the error: `info There appears to be trouble with your network connection. Retrying...`
Trying this fix: https://stackoverflow.com/questions/51508364/yarn-there-appears-to-be-trouble-with-your-network-connection-retrying

ci: increase network request timeout

---

src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/keybindings.cljs
src/cljs/athens/listeners.cljs
src/cljs/athens/views/blocks.cljs

close #646
demo: https://www.loom.com/share/3496f2c683c749c2b3f27ca50898b7df

feat(copy+paste): respect h1/h2/h3 markdown

---

src/cljs/athens/views/settings_page.cljs

 chore(settings): allow any user to opt-out; improve copy

---

src/cljs/athens/athens_datoms.cljs

I copied the uid from my graph.

doc: describe collapse/expand shortcut in Welcome

---

src/cljs/athens/views/blocks.cljs

Thicker checkmark inside checked checkboxes

fix: clearer checkbox checked style

---

src/cljs/athens/views/settings_page.cljs
src/cljs/athens/views/textinput.cljs
src/cljs/athens/views/toggle_switch.cljs

Thank you @shanberg for the design/prototype: 
https://codesandbox.io/s/athens-settings-page-forked-14432?file=/src/components/ToggleSwitch.jsx
Livecoded in the Discord: https://twitter.com/tangjeff0/status/1380585870655246337

enhance(settings): redo settings page

---

src/cljs/athens/style.cljs
src/cljs/athens/views/filesystem.cljs
src/cljs/athens/views/modal.cljs

- Replace Material UI tabs with new picker
- Propertly portal DB dialog(!!)
- Added shadow color to theme
- Minor tweaks to dialog style

enhance(db-picker): Polish db dialog

---

src/cljs/athens/views/app_toolbar.cljs

Just using :title attribute here.
I'm looking into more detailed tooltips with keyboard shortcut hints and better style, but this is a start and very easy.

feat(app-toolbar): basic tooltips

---

src/cljs/athens/subs.cljs

Fixes `deref` error in web app build.

fix: `deref` error in web environment.

---

src/cljs/athens/views.cljs
src/cljs/athens/views/app_toolbar.cljs
src/cljs/athens/views/right_sidebar.cljs

- Toolbar spans full width of app, getting rid of the floating toolbar segments
- Sidebar has same background color as rest of app, to solve insufficient contrast issue in sidebar content
- Minor tweaks to scrollbars and drag handles to solve weird white box issue and improve scrollbar/drag-handle separation and usability

enhance: toolbar, sidebar, and scrolling polish

---

src/cljs/athens/main/core.cljs

https://www.loom.com/share/a67c20f9b9b84f4990ab0c5392c9d75f
Default `backgroundColor` to dark-mode background `#1A1A1A`

enhance(electron): make bg default to dark

---

src/cljs/athens/style.cljs
src/cljs/athens/views/blocks/content.cljs

fix(style): fix mismatched text highlight colors

---

src/cljs/athens/db.cljs

Fixes #728 by sorting references by `:create/time`

enhance(linked-refs): sort references by newest first

---

src/cljs/athens/db.cljs

This reverts commit 19fb97add8e744e24e7d7df3aec2238556cf22da.

revert: "enhance(linked-refs): sort references by newest first (#1124)"

---

src/cljs/athens/core.cljs

Adds support for the [Datalog Console chrome extension](https://chrome.google.com/webstore/detail/datalog-console/cfgbajnnabfanfdkhpdhndegpmepnlmb)

feat(datalog-console): respond to datalog-console messages in browser

---

src/cljs/athens/athens_datoms.cljs
src/cljs/athens/listeners.cljs

Add keyboard shortcuts for Graph view, Pages view and Settings view

feat(keybindings): keybindings for Graph, All Pages, and Settings

---

src/cljs/athens/events.cljs

Bug discussed in #1239 
Prevent expensive and unnecessary recursive calls to previous sidebar item maps

perf(right-sidebar): fix memory+time leak with proper GC of sorted-map #1239

---

src/cljc/athens/parser/impl.cljc
src/cljs/athens/parse_renderer.cljs
src/cljs/athens/views/blocks/content.cljs
test/athens/parser/compatibility_test.clj

Fix(click): Clicking inside a block with hyperlink works on first attempt

---

src/cljs/athens/views/pages/block_page.cljs
src/cljs/athens/views/pages/node_page.cljs

fix: when editing long block-page title, overlaps with child block

---

src/cljs/athens/events.cljs

Display alert that we don't support Undo & Redo yet #1416

Undo & Redo not available in Lan-Party

---

src/cljc/athens/common_events.cljc
src/cljc/athens/common_events/resolver.cljc
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs

Resolves #1413 
Currently, this is WIP,  I don't fully understand what problem this event is solving, also cannot quickly figure out after looking at the current implementation what the problem is and why there are ~120 lines of code for this.

port `:paste` #1413

---

Dockerfile
README.self-hosted.md
project.clj

Create uberjar and update readme about it.
#1474

Build `uberjar` of Lan-Party

---

src/cljc/athens/common_events.cljc
src/cljc/athens/common_events/resolver.cljc
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/components.cljs
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs
src/cljs/athens/views/blocks/textarea_keydown.cljs
src/cljs/athens/views/blocks/toggle.cljs
src/cljs/athens/views/pages/block_page.cljs
src/cljs/athens/views/pages/node_page.cljs
test/athens/common_events/block_test.clj

resolves #1452 #1453 #1454 #1455 #1456

---

src/cljs/athens/events.cljs

Fix typo related to remote event

---

src/cljs/athens/self_hosted/client.cljs

fix: added unlinked-refs to client

---

src/clj/athens/self_hosted/web/datascript.clj
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events/remote.cljs
src/cljs/athens/self_hosted/client.cljs

fix: :enter/bump-up is not working in remote

---

src/clj/athens/self_hosted/web/datascript.clj
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs
src/cljs/athens/self_hosted/client.cljs

fix: close/open blocks

---

src/cljc/athens/common_events.cljc
src/cljc/athens/common_events/resolver.cljc
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs
test/athens/common_events/block_test.clj

Fix: new block in lan party

---

src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs
src/cljs/athens/self_hosted/client.cljs

fix: fix dispatch, uid seq type, and ferry indent/unindent-multi to remote

---

.github/workflows/build.yml
package.json

- test: disable karma test ci for release
- build: set version to 0 so update script increases it

rtc v1 release test

---

src/clj/athens/self_hosted/web/datascript.clj
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/self_hosted/client.cljs

Not only drop events where missing also selected-delete.
Closes #1506

Fix: synced hopefully all the events

---

src/cljc/athens/common_db.cljc

rfct: simplify vector concat -> into

---

src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs

fix: can't delete multiple blocks at once 

---

.carve_ignore
src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs
src/cljs/athens/events/selection.cljs
src/cljs/athens/listeners.cljs
src/cljs/athens/subs.cljs
src/cljs/athens/subs/selection.cljs
src/cljs/athens/views/blocks/content.cljs
src/cljs/athens/views/blocks/context_menu.cljs
src/cljs/athens/views/blocks/core.cljs
src/cljs/athens/views/blocks/textarea_keydown.cljs

Fix: Copy'n'Paste

---

src/cljc/athens/common_events.cljc
src/cljc/athens/common_events/resolver.cljc
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events/remote.cljs

Fix open block add child

---

src/cljs/athens/views/blocks/bullet.cljs

fix: Some bullets are not round

---

src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs
src/cljs/athens/self_hosted/client.cljs
src/cljs/athens/subs.cljs
src/cljs/athens/views/pages/core.cljs

closes #1598 
The summary of the decisions made about this issue can be found here https://github.com/athensresearch/athens/issues/1598#issuecomment-907512172

feat: notify when client is disconnected from server

---

README.self-hosted.md
docker-compose.yml
src/clj/athens/self_hosted/components/config.clj
src/clj/athens/self_hosted/components/datahike.clj

refactor: deep merge config_edn

---

src/cljs/athens/views/blocks/bullet.cljs

fix https://discord.com/channels/708122962422792194/708124073544122399/880029228458975233

fix: bullet too small

---

CHANGELOG.md
package.json
src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/events/selection.cljs
src/cljs/athens/listeners.cljs
src/cljs/athens/subs.cljs
src/cljs/athens/subs/selection.cljs
src/cljs/athens/views/blocks/content.cljs
src/cljs/athens/views/blocks/context_menu.cljs
src/cljs/athens/views/blocks/core.cljs
src/cljs/athens/views/blocks/textarea_keydown.cljs

Original bug report [on Discord](https://discord.com/channels/708122962422792194/800439780910563358/882912277823643670).
Music sponsor of this fix is
https://open.spotify.com/track/0xfMlIW8lS40qvpsUw1l0X?si=e9d4755f0aa44fbd

Fix: Copy'n'Paste for real

---

src/cljs/athens/views/pages/graph.cljs

These changes seem to do the job. Don't have the eye of a designer though, so @shanberg, you might wanna give this is a look
I think this closes #1463

fix(graph-via): Node control is cut off

---

.carve_ignore
project.clj
src/cljc/athens/common_events/resolver.cljc
test/athens/common_events/stress_test.clj

Use `lein test :stress` to run the stress tests.
They will not be ran by default with `lein test`.

test: add stress test

---

src/cljs/athens/electron/db_modal.cljs

Fix https://github.com/athensresearch/athens/pull/1564#discussion_r704963708

fix: import react-dom instead of using missing global

---

test/athens/common_events/stress_test.clj

Add a basic stress test that doesn't use any of common events.

Basic stress test

---

src/cljs/athens/electron/db_modal.cljs
src/cljs/athens/events/remote.cljs
src/cljs/athens/self_hosted/client.cljs

And notify user with New DB creation, for now, until we have something
decent to present to a user.

Fix: escape hatch when connecting to remote

---

src/cljs/athens/db.cljs

Fix: Sort linked references by date descending.

---

src/cljs/athens/core.cljs
src/cljs/athens/events.cljs
src/cljs/athens/util.cljs
src/cljs/athens/views.cljs

 fix: set body classes

---

src/cljs/athens/events.cljs
src/cljs/athens/router.cljs

Followup to #1669, that impl didn't work on daily notes.

fix: always focus first child, even on daily notes

---

src/clj/athens/self_hosted/web/datascript.clj
src/cljc/athens/common_db.cljc
src/cljc/athens/common_events/graph/schema.cljc
src/cljc/athens/common_events/resolver/atomic.cljc
src/cljs/athens/effects.cljs
test/athens/common_events/orderkeeper_test.clj

Introduces `common-db/orderkeeper`

Feature: block ordering

---

README.self-hosted.md
docker-compose.yml

Followup from discussion on discord: https://discord.com/channels/708122962422792194/802652338619285594/892682409257091092

fix: don't release docker-compose that attempts to build images

---

src/cljc/athens/common/utils.cljc
src/cljc/athens/common_db.cljc
src/cljc/athens/common_events/graph/ops.cljc
src/cljc/athens/common_events/resolver/atomic.cljc
src/cljs/athens/events.cljs
src/cljs/athens/self_hosted/client.cljs

- fix: improve logging for paste
- fix: last block on an empty page should not be 1
- rfct: faster page lookups
- fix: improve compat-position warning
- feat: log resolve-transact! total time
- fix: clear session list on reconnect

slow copy paste

---

deps.edn
script/docker-run-lan-party.sh

Includes fix for https://github.com/fluree/db/issues/125

build: bump fluree

---

src/clj/athens/self_hosted/web/datascript.clj
src/cljc/athens/common_events.cljc
src/cljc/athens/common_events/resolver.cljc
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events.cljs
src/cljs/athens/self_hosted/client.cljs

open block add child done using atomic ops

---

src/clj/athens/self_hosted/web/datascript.clj
src/cljc/athens/common_db.cljc
src/cljc/athens/common_events.cljc
src/cljc/athens/common_events/graph/atomic.cljc
src/cljc/athens/common_events/resolver.cljc
src/cljc/athens/common_events/resolver/atomic.cljc
src/cljc/athens/common_events/schema.cljc
src/cljs/athens/events.cljs
src/cljs/athens/self_hosted/client.cljs
src/cljs/athens/views/left_sidebar.cljs
test/athens/common_events/atomic_ops/shortcut_test.cljc

shortcut move atomic op

---

package.json
src/js/components/Button/Button.stories.tsx
src/js/components/Button/Button.tsx
src/js/components/Button/index.ts
src/js/components/Menu/hooks/useMenu.ts
src/js/components/concept/Welcome/Welcome.stories.tsx
src/js/components/concept/Welcome/Welcome.tsx
src/js/components/concept/Welcome/components/AddDatabase.tsx
src/js/components/concept/Welcome/components/DatabasesList.tsx
src/js/components/concept/Welcome/components/Item.tsx
src/js/components/concept/Welcome/components/JoinDatabase.tsx
src/js/components/concept/Welcome/components/SkeletonItem.tsx
src/js/components/concept/Welcome/mockData.ts
yarn.lock

Fills out Welcome storybook section with components for welcome workflow

add welcome screen components

---

package.json
shadow-cljs.edn
yarn.lock

Should improve debugging efforts in prod.

build: add source maps and pseudo names to electron build

---

package.json
src/clj/athens/self_hosted/components/datascript.clj
src/clj/athens/self_hosted/components/fluree.clj
src/clj/athens/self_hosted/components/web.clj
src/clj/athens/self_hosted/event_log.clj
src/clj/athens/self_hosted/web/datascript.clj
src/cljc/athens/async.cljc
src/cljs/athens/effects.cljs
src/cljs/athens/events/remote.cljs

- fix: save event to log inside the same lock as db transaction
- fix: don't print whole remote-db config
- fix: timeout on health check
- feat: handle errors and reconnect on add-event!
- build: add fluree dev script

fluree timeout

---

src/cljs/athens/self_hosted/presence/views.cljs

Same as toolbar presence is doing already.

fix: remove nils from inline presence too

---

src/cljs/athens/views/blocks/autocomplete_search.cljs
src/cljs/athens/views/blocks/core.cljs
src/cljs/athens/views/blocks/textarea_keydown.cljs

Use `/template` or type `;;` to look for a block to use as a template.
That blocks children will be inserted in place of the calling block, as if pasted.

feat: templates

---

src/cljs/athens/electron/window.cljs
src/cljs/athens/views/app_toolbar.cljs

[Linked issue](https://github.com/athensresearch/athens/issues/1890)

Fix minimize, maximize, close buttons not working

---

src/cljc/athens/common_events/graph/ops.cljc
src/cljs/athens/events.cljs
src/cljs/athens/views/blocks/textarea_keydown.cljs

fix: support updating on block remove and merge.

---

src/cljc/athens/parser/impl.cljc
src/cljs/athens/parse_renderer.cljs
test/athens/parser/impl_test.clj

Feature: page link & block ref aliases

---

src/cljs/athens/views/pages/node_page.cljs

fix #1914 caused by #1351

---

deps.edn
doc/adr/0019-rollback-optimizations.md
src/cljc/athens/common_events/resolver/atomic.cljc
src/cljc/event_sync/core.cljc
src/cljs/athens/db.cljs
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs
src/cljs/athens/self_hosted/client.cljs
test/athens/common_events/atomic_ops/block_move_test.cljc

- feat: resolve-transact! returns the transacted datoms
- feat: resolve-transact! can also transact without middleware
- feat: use undo instead of reset for rollback
- rfct: add note about renaming event-sync
- docs: update rollback optimizations ADR with MVP
- build: update datascript

Undo based optimistic rollback

---

src/cljs/athens/electron/db_menu/db_list_item.cljs
src/cljs/athens/electron/dialogs.cljs

v1 - https://www.loom.com/share/e94c905163e54f4d937c823d4aabbd20
v2 in response to Alex and Stuart's feedback - https://www.loom.com/share/f52ea62f5053457191b63a40bc7f7971

enhance(db-picker): allow users to remove dbs from list

---

src/cljs/athens/events.cljs

Is this something that needs tests?
https://www.loom.com/share/8380f9e48ed44cc6874497a13aadb1ef

fix(indent): if prev sibling block is closed on indent, open

---

src/cljc/athens/common_db.cljc
src/cljs/athens/events.cljs
src/cljs/athens/events/remote.cljs
src/cljs/athens/views/pages/node_page.cljs

- fix: guard pulls in common-db
- fix: must check if page was removed before removing it
- fix: also navigate on delete if uid matches

page remove pull

---

deps.edn
dev/clj/config.edn
docker-compose.yml
package.json
src/clj/athens/self_hosted/components/datascript.clj
src/clj/athens/self_hosted/components/web.clj
src/clj/athens/self_hosted/event_log.clj
src/clj/athens/self_hosted/save_load.clj
src/clj/athens/self_hosted/web/datascript.clj
src/clj/athens/self_hosted/web/persistence.clj
src/clj/config.default.edn
src/cljc/athens/common_db.cljc
src/cljc/athens/common_events/resolver/atomic.cljc
test/athens/common_db_test.cljc

- feat: add athens.self-hosted.web.persistence ns
- feat: add :datascript :persist-base-path to server config
- rfct: make most persistence ns fns private
- rfct: use /datascript/persist instead of just /persist/
- feat: persist server datascript db

datascript persist

---

src/js/components/Block/components/Content.tsx

- Fixes an issue where various elements block contents couldn't be clicked (checkboxes, embeds, etc.)

fix: more elements interactable within blocks

---

src/cljs/athens/self_hosted/presence/views.cljs
src/js/components/PresenceDetails/PresenceDetails.tsx
src/js/theme/theme.js

- Toasts react to current color mode instead of being a fixed color
- Toast 'info' status color uses a better color
- refactor: fully replace colors object with semantic tokens

Polish-toasts

---

src/cljs/athens/electron/monitoring/core.cljs

Reverts athensresearch/athens#2112

Revert "Revert "fix: Feature block link correct counting""

---

src/cljs/athens/electron/db_picker.cljs
src/cljs/athens/views/blocks/textarea_keydown.cljs

feat: add a slash command to insert own name link

---

src/js/components/Block/Content.tsx

- Fix content/textarea sizing issue

fix: force consistent typography on block text and textarea

---

src/js/components/AllPagesTable/AllPagesTable.tsx

- Fixes possible error when trying to display pages with no created date
- Fixes page width
- Reduces some hacky overrides

Virtualize all pages

---

src/cljs/athens/views/pages/node_page.cljs
src/js/components/AppToolbar/AppToolbar.tsx
src/js/components/Confirmation/Confirmation.tsx
src/js/components/Page/Page.tsx
src/js/theme/theme.js

- Restores the confirmation dialog for page merge
- Adds new color schemes for buttons that should be subtle or highlighted

Fix alert confirm

---

src/cljs/athens/listeners.cljs

Definitely not the last of the embed problems.

fix: copy on embed blocks

---

src/cljs/athens/electron/db_modal.cljs

Fixes unexpected insertion point movement in database dialogs

fix: don't control dialog inputs

---

src/cljs/athens/views/pages/block_page.cljs

show button that would allow user to open block in main

enhance: if a block open in right sidebar is not in main view,

---

src/cljs/athens/views/blocks/core.cljs
src/js/components/Block/Anchor.tsx
src/js/components/Block/Container.tsx
src/js/components/utils/useContextMenu.tsx

- Adds new useContextMenu hook
- Reimplements block anchor button using new hook
- Adds context menu actions to block containers

Add useContextMenu hook

---

src/js/components/PresenceDetails/PresenceDetails.tsx
src/js/components/ProfileSettingsDialog/ProfileSettingsDialog.tsx

- Show current user in toolbar presence
- Fix a cause of "missing username" error when reloading the page
- Show page name for users on other pages
- Disable user menu items when they can't be navigated to

Improve presence in toolbar

---

src/cljs/athens/views/blocks/editor.cljs
src/cljs/athens/views/pages/node_page.cljs
src/js/components/Block/Anchor.tsx
src/js/components/Block/Container.tsx
src/js/components/References/InlineReferences.tsx
src/js/components/utils/useContextMenu.tsx
test/e2e/block-context-menu.spec.ts

Reverts athensresearch/athens#2238

Revert "Move actions to block anchor"

---

src/js/components/Block/Reactions.tsx

Fix clicking other people's reactions.
Also simplifies the styling of reactions.

fix: can click other people's reactions

---

src/cljs/athens/db.cljs
src/cljs/athens/views/athena.cljs

- fix: autocomplete should be autoComplete
- rfct: optimize search-in-block-content for comments
- rfct: remove unused history listener

search perf

---

src/cljs/athens/views.cljs
src/cljs/athens/views/app_toolbar.cljs
src/cljs/athens/views/pages/core.cljs
src/cljs/athens/views/pages/settings.cljs

enhance: use settings as a modal, not as a page

---

src/cljs/athens/views/notifications/popover.cljs
src/js/components/Inbox/Inbox.tsx

- also, show notifications icon in app toolbar, even if number of notifications is 0

fix: onArchive stopPropagation to not navigate to notif

---

src/cljc/athens/common_events/graph/ops.cljc
src/cljs/athens/events.cljs
src/cljs/athens/views/blocks/core.cljs

- fix: enter on prop should split block
- fix: block-el should prioritize the reactive props

fix: enter on prop should split block

---

src/cljc/athens/common_events/graph/ops.cljc
src/cljs/athens/self_hosted/presence/subs.cljs

- rfct: current-user is You when not remote
- rfct: remove debug message

presence pkm

---

src/cljs/athens/components.cljs
src/cljs/athens/types/default/view.cljs
src/cljs/athens/views/blocks/core.cljs

- fix: embeds should show children
- fix: edit on embed should edit transcluding block

embeds again

---

src/js/components/PresenceDetails/PresenceDetails.tsx

- Disable the person button when clicking the person button would otherwise lead to an error

fix: disable user button when user not on a page

---

src/cljs/athens/electron/db_modal.cljs
src/js/theme/theme.js

Adds new tab style for things like sidebar tabs.

feat: add rect tabs style, make default

---

src/cljs/athens/views/blocks/core.cljs

before ![image](https://user-images.githubusercontent.com/8952138/187473780-8e63366e-3001-4cdd-8731-d2144abb5708.png)
after ![image](https://user-images.githubusercontent.com/8952138/187473620-264501d1-754b-4557-a151-b4c5ac586388.png)

Checkmark icon for convert block to task

---

src/cljs/athens/types/query/view.cljs
src/cljs/athens/views/blocks/core.cljs
src/cljs/athens/views/pages/node_page.cljs
src/js/components/App/ContextMenuContext.tsx
src/js/components/Block/Container.tsx
src/js/components/Query/KanbanBoard.tsx
src/js/components/Query/Query.tsx
src/js/components/hooks/useOverflowShadow.tsx

Nicer style for cards on query boards

Improve kanban queries styling

---

src/cljs/athens/types/tasks/view.cljs
src/js/components/Block/Taskbox.tsx
src/js/theme/theme.js

- task checkboxes are the same height as regular todos
- tasks look simpler when reffed
- tasks use fewer DOM elements

Improve task appearance and fix status

---

src/cljs/athens/types/query/view.cljs
src/cljs/athens/views/comments/inline.cljs
src/js/components/Block/BlockFormInput.tsx
src/js/components/ModalInput/ModalInputPopover.tsx
src/js/components/Query/KanbanBoard.tsx

Also remove some unused TS component code

feat: add block editor to card edit popover

---

src/js/components/Layout/RightSidebar.tsx
src/js/components/Page/Page.tsx

Restores proper(-ish) width to items in right sidebar

fix: right sidebar items shouldn't be squished

---

src/cljs/athens/types/tasks/handlers.cljs
src/cljs/athens/types/tasks/inline_task_title.cljs
src/cljs/athens/types/tasks/view.cljs
src/cljs/athens/views/left_sidebar/tasks.cljs

And allowing to edit `:task/status` inline.
Uncovers a bug with task outline not having reactive status.

feat: Task Ref be more like Block Ref

---

src/js/components/Layout/List.tsx
src/js/components/Layout/RightSidebar.tsx
src/js/components/SidebarShortcuts/List.tsx
src/js/theme/theme.js

Makes sidebar items more usable by using card style, also saving space

Restyle sidebar els

---

src/js/components/Block/Container.tsx

Comments boxes should fit the body of the block, not the extra stuff on the side

fix: comments boxes shouldn't stretch too far

---

src/cljs/athens/types/tasks/view.cljs
src/cljs/athens/types/tasks/view/inline_task_title.cljs

Includes callback fns on embedded tasks so the embedded task doesn't fail to render

fix error when embedding task

---

src/cljs/athens/views/left_sidebar/core.cljs

Hides tasks from sidebar when tasks feature flag is off

fix: left sidebar respects tasks ff

---

src/cljs/athens/events.cljs
src/cljs/athens/views/comments/core.cljs
src/cljs/athens/views/comments/inline.cljs

rename comment and comment-thread properties

---

src/cljs/athens/views/notifications/core.cljs
src/cljs/athens/views/notifications/popover.cljs

Reverts athensresearch/athens#2402

Revert "Rename notification property values"

---

src/cljs/athens/events.cljs
src/cljs/athens/views/comments/core.cljs
src/cljs/athens/views/comments/inline.cljs

Reverts athensresearch/athens#2399

Revert "rename comment and comment-thread properties"
